#Linux

# Ubuntu
- name: Adicionar apt key de um keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E084DAB9
  when: ansible_distribution == 'Ubuntu'

- name: Adicionar repositório para r-project - Linux Ubuntu
  apt_repository:
    repo: deb https://cloud.r-project.org/bin/linux/ubuntu trusty
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Instalar os pacotes para o r-project - Linux Ubuntu
  apt: name={{item}} state=latest
  with_items:
    - r-base
    - r-base-dev
    - r-cran-rjava
    - libjpeg62
  when: ansible_distribution == 'Ubuntu'

#Windows
- name: Instalar o R - Windows
  win_chocolatey:
    name: '{{ item }}'
    state: latest
  with_items:
  - r.project
  - r.studio
  when: ansible_os_family == 'Windows'
