#Linux

# Debian e Ubuntu
- name: Instalar os pacotes para o r-project - Linux
  apt: name={{item}} state=latest
  with_items:
    - r-base
    - r-base-dev
    - libatlas3-base
    - r-cran-rjava
    - libjpeg62
  when: ansible_os_family == 'Debian'

- name: Instalar bibliotecas para o r-studio - Linux
  apt: name={{item}} state=latest
  with_items:
    - r-cran-gdata
    - r-cran-gmodels
    - r-cran-gtools
  when: ansible_os_family == 'Debian'

- name: Install a .deb R-Studio - Linux
  apt:
    deb: https://download1.rstudio.org/rstudio-xenial-1.1.456-amd64.deb
  when: ansible_os_family == 'Debian'

#Windows
- name: Instalar o R - Windows
  win_chocolatey:
    name: "{{item}}"
    #version: latest
  with_items:
    - r.project
    - r.studio
  when: ansible_os_family == 'Windows'

- name: Atalho para o r-project
  win_shortcut:
    description: Atalho para o r-project
    src: '%ProgramFiles%\R\R-3.5.1\bin\x64\Rgui.exe'
    dest: '%Public%\Desktop\R.lnk'
    icon: '%ProgramFiles%\R\R-3.5.1\bin\x64\Rgui.exe,0'
    args: '--cd-to-userdocs'
    state: present
  when: ansible_os_family == 'Windows'
