---
#Linux
- name: Arquivo do source list - Debian stretch
  copy:
    src: sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_release == 'stretch'
  notify:
    - update apt cache

- apt_repository:
    repo: deb http://debian.pop-sc.rnp.br/debian jessie-backports main contrib non-free
    state: absent
    filename: ftp_debian_org_debian