---
- name: Instalando o pacote necessario
  apt: name=x11vnc state=latest
  
- name: Copiando o script para o profile
  copy:
    src: x11vnc.sh
    dest: /etc/profile.d/x11vnc.sh
    owner: root
    group: root
    mode: 0644
