---
#Linux

- name: Extraindo o irpf.tgz
  unarchive:
    src: irpf19.tgz
    dest: /usr/local/
    creates: /usr/local/IRPF2019
  when: ansible_os_family == 'Debian'

- name: Definindo as permissões corretas do IRPF
  file:
    path: /usr/local/IRPF2019
    owner: root
    group: root
    mode: 0777
    recurse: yes
  when: ansible_os_family == 'Debian'

- name: Criando o arquivo IRPF2019-desktop.desktop
  copy:
    src: IRPF2019-desktop.desktop
    dest: /usr/share/applications/IRPF2019-desktop.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

#Windows

- name: Instala o IRPF 2018 v1.5 - Windows
  win_package:
    path: http://downloadirpf.receita.fazenda.gov.br/irpf/2019/irpf/arquivos/IRPF2019Win32v1.0.exe
    arguments: /mode silent
    product_id: IRPF2019
  when: ansible_os_family == 'Windows'
