---
#Linux


- name: Extraindo o irpf2020.bz
  unarchive:
    src: irpf2020.bz
    dest: /usr/local/
    creates: /usr/local/IRPF2020
  when: ansible_os_family == 'Debian'

- name: Definindo as permissões corretas do IRPF
  file:
    path: /usr/local/IRPF2020
    owner: root
    group: root
    mode: 0777
    recurse: yes
  when: ansible_os_family == 'Debian'

- name: Criando o arquivo IRPF2020-desktop.desktop
  copy:
    src: IRPF2020-desktop.desktop
    dest: /usr/share/applications/IRPF2020-desktop.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

#Windows

- name: Instala o IRPF 2020 v1.2 - Windows
  win_package:
    path: http://downloadirpf.receita.fazenda.gov.br/irpf/2020/irpf/arquivos/IRPF2020Win32v1.2.exe
    arguments: /mode silent
    product_id: IRPF2020
  when: ansible_os_family == 'Windows'
