---
- name: Extraindo o irpf.tgz
  unarchive:
    src: irpf18.tgz
    dest: /usr/local/
    creates: /usr/local/IRPF2018 
  when: ansible_os_family == 'Debian'

- name: Definindo as permissões corretas do IRPF
  file:
    path: /usr/local/IRPF2018
    owner: root
    group: root
    mode: 0777
    recurse: yes
  when: ansible_os_family == 'Debian'

- name: Criando o arquivo IRPF2018-desktop.desktop
  copy:
    src: IRPF2018-desktop.desktop
    dest: /usr/share/applications/IRPF2018-desktop.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'
