---
- name: Instalar o Foxit (Windows)
  win_chocolatey:
    name: foxit
    state: latest
  when: ansible_os_family == 'Windows'

- name: Extraindo o foxitsoftware.tgz
  unarchive:
    src: https://discovirtual.ifsc.edu.br/index.php/s/5exGvwLhycd6AKF/download
    dest: /opt/
    creates: /opt/foxitsoftware
    remote_src: yes
  when: ansible_os_family == 'Debian'

- name: Definindo as permissões corretas do Foxit
  file:
    path: /opt/foxitsoftware
    owner: root
    group: root
    mode: 0755
    recurse: yes
  when: ansible_os_family == 'Debian'

- name: Criando o arquivo foxit.desktop
  copy:
    src: foxit.desktop
    dest: /usr/share/applications/foxit.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'
