#Linux
- name: Instalar pacotes padroes de laboratorios - Linux
  apt: name={{item}} state=latest
  with_items:
    - ethtool
    - minicom
    - nmap
    - geany
    - unrar
    - audacity
    - gimp
    - inkscape
    - latexila
    - scratch
    - ntfs-3g
    - android-tools-adb
    - iperf
    - xournal 
    - ipcalc
    - tcpdump
    - snmp-mibs-downloader
  when: ansible_os_family == 'Debian'

#Windows e Linux
- include_role:
    name: virtualbox
- include_role:
    name: wireshark
- include_role:
    name: arduino