# - hosts: laboratorios_lin
#   roles:
#     - final_semestre

# - hosts: laboratorios_win
#   roles:
#     - final_semestre

# LIMPA TEMP WINDOWS
- hosts: laboratorios_win
  roles: 
    - role: limpa_temp_windows
      play: 0
      # play: 0 desativa
      # play: 1 ativa

# ATUALIZA MAC
# SEMPRE VERIFICAR O HOST QUE QUER ATINGIR
- hosts: laboratorios_lin
  roles: 
    - role: atualiza_mac
      play: 0
      # play: 0 desativa
      # play: 1 ativa

## DESCOMENTAR PARA CORRIGIR O EPOPTES, PEGAR AS CHAVES DO SERVER. COMENTAR NOVAMENTE DEPOIS.
## LEMBRAR DE RODAR COM A OPÇÃO -l GRUPO_DO_LAB
# - hosts: laboratorios_lin
#   tasks:
#     - name: Pegar as chaves do epoptes server no cliente - Linux
#       shell: /usr/sbin/epoptes-client -c
#       when: ansible_os_family == 'Debian'


# - hosts: laboratorios_lin
#   roles: 
#     - role: restaura_vms
#       nome_vms:
#         - 1-Grafico.bz
#         - 2-Grafico.bz
#         - 3-Grafico.bz
#         - 4-Grafico.bz
#         - 5-Grafico.bz
#         - 6-Grafico.bz
#         - 1-Servidor.bz
#         - 2-Servidor.bz
#         - 3-Servidor.bz
#         - 4-Servidor.bz
#         - 5-Servidor.bz
#         - 6-Servidor.bz
#         - 7-Servidor.bz
#         - 8-Servidor.bz
#         - 9-Servidor.bz
#         - 10-Servidor.bz