---
- name: Programas administrativos
  hosts: administrativos
  gather_facts: false
  tasks:
    - meta: clear_host_errors
  roles:
    - programas_padroes

- name: Teste novos modulos
  hosts: teste
  tasks:
    - meta: clear_host_errors
  roles:
    - role: grycap.ntp
      ntp_config_server: [pool.ntp.br, ntp.cais.rnp.br, ntp.ufsc.br]

    - role: tersmitten.apt
      apt_manage_sources_list: true
      apt_debian_mirror: http://debian.pop-sc.rnp.br/debian
      apt_debian_contrib_nonfree_enable: true
      apt_dpkg_configure: true
      apt_install: [curl, pinta]
      apt_remove: transmission-gtk
    
    - role: tumf.systemd-service
      systemd_service_name: "x11vnc"
      systemd_service_Unit_Description: Acesso Remoto
      systemd_service_Unit_After: syslog.target 
      systemd_service_Service_PIDFile: /var/run/x11vnc.pid 
      systemd_service_Service_ExecStart: /usr/bin/x11vnc -auth guess -noxdamage -rfbport 5900 -shared -forever -nopw -accept popup:0 
      systemd_service_Service_Restart: on-abort
