---
- hosts: laboratorios_lin
  roles:
    - sources_list
    - programas_padroes
    - papel_de_parede_e_icones
    - role: geerlingguy.ntp
      ntp_timezone: America/Sao_Paulo
      ntp_manage_config: true
      ntp_servers:
        - "pool.ntp.br iburst"
        - "ntp.cais.rnp.br iburst"
        - "ntp.ufsc.br iburst"

- hosts: laboratorios_lin:!labcad1
  roles:
    - role: debops.grub
      grub_users:
        - name: 'su'
          password: 'NBLWAThUq5'
          superuser: True
      grub_default: '0'
      grub_timeout_hardware: 0
      grub_timeout_virtual: 0

- hosts: laboratorios_win
  roles:
    - programas_padroes
    - papel_de_parede_e_icones
    - windows_update
  tasks:
    - name: Configura servidores NTP para o Windows
      win_shell: net start w32time ;	w32tm /config /manualpeerlist:"a.st1.ntp.br b.st1.ntp.br c.st1.ntp.br gps.ntp.br" /syncfromflags:manual /reliable:YES /update ; net stop w32time ; net start w32time ; w32tm /config /update ; w32tm /resync ; w32tm /resync ; New-Item c:\gatilho_ntp.txt -type file
      args:
        creates: C:\gatilho_ntp.txt

