---
- hosts: administrativos_lin
  roles:
    - sources_list
    - programas_padroes_adm
    - config_padrao_adm
    - acesso_remoto
    - fonte_garamound
    - papel_de_parede_e_icones

# Chamado do Jorge casagrande pedindo para desativar o desligamento na máquina dele IFSC#2018112610001119
# Chamado do Diego Medeiros pedindo para desativar o desligamento na máquina dele IFSC#2018112810000143
- hosts: administrativos_lin:!sj-lin-cotel-38112.maquinas.sj.ifsc.edu.br:!sj-lin-des2-744927.maquinas.sj.ifsc.edu.br
  roles:
    - auto_desligamento

# PC do Prof Diego usa Gnome + GDM3
- hosts: administrativos_lin:!sj-lin-des2-744927.maquinas.sj.ifsc.edu.br:!patrim:!biblio
  roles:
    - ingressa_ldap

- hosts: administrativos_lin:!labfisica
  roles:
    - role: debops.grub
      grub_users:
        - name: 'su'
          password: 'NBLWAThUq5'
          superuser: True
      grub_default: '0'
      grub_timeout_hardware: 0
      grub_timeout_virtual: 0
      apt_install__enabled: false
      apt__enabled: false

- hosts: administrativos_win
  roles:
    - programas_padroes_adm
    - config_padrao_adm
    - acesso_remoto
    - papel_de_parede_e_icones
    - windows_update
    - ingressa_ldap
    - auto_desligamento
