---
- hosts: laboratorios_lin
  roles:
    - sources_list
    - programas_padroes_labs
    - config_padrao_labs
    - papel_de_parede_e_icones
    - role: debops.grub
      grub_users:
        - name: 'su'
          password: 'NBLWAThUq5'
          superuser: True
      grub_default: '0'
      grub_timeout_hardware: 0
      grub_timeout_virtual: 0
      apt_install__enabled: false
      apt__enabled: false

- hosts: laboratorios_win
  roles:
    - programas_padroes_labs
    - config_padrao_labs
    - papel_de_parede_e_icones
    - windows_update
