---
- hosts: laboratorios_lin
#  ignore_unreachable: true
  roles:
    - sources_list
    - programas_padroes_labs
    - config_padrao_labs
    - papel_de_parede_e_icones


- hosts: laboratorios_win
#  ignore_unreachable: true
  roles:
    - programas_padroes_labs
    - config_padrao_labs
    - papel_de_parede_e_icones
    - windows_update
