- hosts: ctic
  roles:
    - code
    - teamviewer
    - virtualbox
    - rambox
    - ingressa_ldap
  tasks:
  - name: Instalar os pacotes para o Ansible do stretch-backports - Linux Debian
    apt: name=ansible state=latest default_release=stretch-backports
  - name: Pacotes padroes da CTIC
    apt: name={{ packages }} state=latest
    vars:
      packages:
      - docker
      - keepassx
      - konsole
      - nfs-common
      - curl
      - ethtool
      - git
      - gparted
      - vinagre
      - samba
      - tcpdump
      - usbutils
      - sshfs
      - net-tools
      - dnsutils
  - name: Adiciona no grupo docker
    user:
      name: "{{item}}"
      groups: docker
      append: yes
    with_items:
      - rmartins
      - humbertos
      - gabriel.souza
      - marcelo.alejandro
      - etorresini
    when: ansible_os_family == 'Debian'

##################  Maquina do RICARDO  ##################
- hosts: sj-lin-ctic-744396.maquinas.sj.ifsc.edu.br
  roles:
    - kubernetes
    - softwares_remotos
    - role: geerlingguy.nfs
      nfs_exports: [ "/dados *(rw,sync,no_root_squash)" ]
    # - role: bertvv.samba
    #   samba_shares:
    #     - name: ctic
    #       comment: 'O local mais seguro de todos'
    #       path: /dados
    #       browseable: yes
    #       create_mode: '777'
    #       directory_mode: '777'
    #       valid_users: '%S'
    #       writable: yes
    #       read_only: no
    #       guest_ok: yes
    #   samba_users:
    #     - name: USERNAME
    #       password: PASSWORD
  tasks:
  - name: Pacotes do Ricardo
    apt: name={{ packages }} state=latest
    vars:
      packages:
      - k3b
      - keychain
      - dcfldd
      - lm-sensors
      - nautilus-dropbox
      - unzip
      - vlan
      - python3-pip
      - python3-tk
      - gir1.2-appindicator3-0.1
      - python-appindicator
      - virtualenv
  - pip:
      name: pywinrm
##########################################################
