#- hosts: ctic
#  roles:
#    - code
#    - teamviewer
#    - virtualbox
- hosts: sj-lin-ctic-744396.maquinas.sj.ifsc.edu.br
  roles:
    - code
    - kubernetes
    - docker
    - rambox
    - teamviewer
    - virtualbox
    - softwares_remotos
    - role: geerlingguy.nfs
      nfs_exports: [ "/dados *(rw,sync,no_root_squash)" ]
#    - role: bertvv.samba
#      samba_shares:
#      - name: ctic
#        comment: 'O local mais seguro de todos'
#        path: /dados
#        browseable: yes
#        create_mode: '777'
#        directory_mode: '777'
#        valid_users: '%S'
#        writable: yes
#        read_only: no
#        guest_ok: yes
  tasks:
  - name: Instalar os pacotes para o Ansible do stretch-backports - Linux Debian
    apt: name=ansible state=latest default_release=stretch-backports
  - name: Pacotes do Ricardo
    apt: name={{item}} state=latest
    with_items:
      - keepassx
      - k3b
      - konsole
      - keychain
      - nfs-common
      - curl
      - dcfldd
      - ethtool
      - git
      - gparted
      - lm-sensors
      - vinagre
      - nautilus-dropbox
#      - samba
      - tcpdump
      - unzip
      - usbutils
      - vlan
      - sshfs
      - python-pip
      - virtualenv
  - pip:
      name: pywinrm