- hosts: ctic
  any_errors_fatal: true
  roles:
    - code
    - docker
    # - teamviewer
    # - virtualbox
    - rambox
    # - ingressa_ldap
    - rke
  tasks:
  - name: Instalar os pacotes para o Ansible #do buster-backports - Linux Debian
    apt: name=ansible state=latest #default_release=buster-backports
  - name: Pacotes padroes da CTIC
    apt: name={{ packages }} state=latest
    vars:
      packages:
      - keepassx
      - konsole
      - nfs-common
      - curl
      - ethtool
      - git
      - gparted
      - vinagre
      - samba
      - tcpdump
      - usbutils
      - sshfs
      - net-tools
      - dnsutils
  - name: Adiciona no grupo docker
    user:
      name: "{{item}}"
      groups: docker
      append: yes
    with_items:
      - rmartins
      - humbertos
      - gabriel.souza
      - marcelo.alejandro
      - etorresini
    when: ansible_os_family == 'Debian'

##################  Maquina do RICARDO  ##################
- hosts: sj-lin-ctic-744521.maquinas.sj.ifsc.edu.br
  any_errors_fatal: true
  roles:
    - kubernetes
    # - softwares_remotos # ruim no buster
    - role: geerlingguy.nfs
      nfs_exports: [ "/dados *(rw,sync,no_root_squash)" ]
    # - role: bertvv.samba
    #   samba_shares:
    #     - name: ctic
    #       comment: 'O local mais seguro de todos'
    #       path: /dados
    #       browseable: yes
    #       create_mode: '777'
    #       directory_mode: '777'
    #       valid_users: '%S'
    #       writable: yes
    #       read_only: no
    #       guest_ok: yes
    #   samba_users:
    #     - name: USERNAME
    #       password: PASSWORD
  tasks:
  - name: Pacotes do Ricardo
    apt: name={{ packages }} state=latest
    vars:
      packages:
      - k3b
      - keychain
      - dcfldd
      - lm-sensors
      # - nautilus-dropbox # ruim no buster
      - unzip
      - vlan
      - python3-pip
      - python-pip
      - python3-tk
      - gir1.2-appindicator3-0.1
      # - python-appindicator # ruim no buster
      - virtualenv
  - pip:
      name: pywinrm
##########################################################
