#- hosts: ctic
#  roles:
#    - code
#    - teamviewer
#    - virtualbox
- hosts: sj-lin-ctic-744396.maquinas.sj.ifsc.edu.br
  roles:
#    - code
#    - teamviewer
    - virtualbox
    - softwares_remotos
    - role: geerlingguy.nfs
      nfs_exports: [ "/dados *(rw,sync,no_root_squash)" ]
  tasks:
  - name: Pacotes do Ricardo
    apt: name={{item}} state=latest
    with_items:
      - keepassx
      - k3b
      - konsole
      - keychain
      - nfs-common
      - curl
      - dcfldd
      - ethtool
      - git
      - gparted
      - lm-sensors
      - vinagre
      - samba
      - tcpdump
      - unzip
      - usbutils
      - vlan
  - name: Install a .deb Microsoft VS Code - Linux Debian
    apt:
      deb: https://go.microsoft.com/fwlink/?LinkID=760868
 
 
