- hosts: des1
  any_errors_fatal: true
  roles:
    - packettracer
    - kile
    - programas_padroes_labs

- hosts: sj-lin-des1-744935.maquinas.sj.ifsc.edu.br #Claudia
  tasks:
    - name: Pacotes da Claudia
      apt:
        state: latest
        pkg:
        - nautilus-dropbox
