- hosts: des2
#  ignore_unreachable: true
  roles:
    - packettracer
    - kile
    - programas_padroes_labs

- hosts: des2
#  ignore_unreachable: true
  roles:
    - role: grub
      tipo: grub_lin

- hosts: sj-lin-des2-744927.maquinas.sj.ifsc.edu.br #Diego
#  ignore_unreachable: true
  roles:
    - ingressa_ldap_gdm
  tasks:
  - name: Pacotes do Diego
    apt: name={{item}} state=latest
    with_items:
      - nautilus-dropbox
  - name: Install a .deb Mendeley Desktop - Linux Debian
    apt:
      deb: https://discovirtual.ifsc.edu.br/index.php/s/vBroCEKQ94qeEFv/download
    when: ansible_os_family == 'Debian'
