# Linux

- hosts: cad1_lin
  roles:
    - role: debops.grub
      grub_users:
        - name: 'su'
          password: 'NBLWAThUq5'
          superuser: True
      grub_default: '2'
      grub_timeout_hardware: 15
      grub_timeout_virtual: 15
      apt_install__enabled: false
      apt__enabled: false
  tasks:
  - name: Monta /dev/sda3 em /media/aluno/trabalhos fstab - Linux
    mount:
      path: /media/aluno/trabalhos
      src: /dev/sda3
      fstype: vfat
      state: present
    when: ansible_os_family == 'Debian'

- hosts: cad1_lin:!sj-lin-cad1-37247.maquinas.sj.ifsc.edu.br
  roles:
    - epoptes_client

- hosts: sj-lin-cad1-37247.maquinas.sj.ifsc.edu.br #Maquina do professor
  roles:
    - epoptes_server
    - ingressa_ldap

# Windows

- hosts: cad1_win
  roles:
    - programas_padroes_labs
    - config_padrao_labs
    - papel_de_parede_e_icones
    - windows_update

- hosts: sj-cad1-37247.maquinas.sj.ifsc.edu.br #Maquina do professor
  roles:
    - ingressa_ldap