#Linux

- hosts: cad2_lin
  roles: 
    - role: grub
      tipo: grub_win
  tasks:
  - name: Monta /dev/sda3 em /media/aluno/trabalhos fstab - Linux
    mount:
      path: /media/aluno/trabalhos
      src: /dev/sda3
      fstype: vfat
      state: present
    when: ansible_os_family == 'Debian'

- hosts: cad2_lin:!sj-lin-cad2-38841.maquinas.sj.ifsc.edu.br
  roles:
    - epoptes_client

- hosts: sj-lin-cad2-38841.maquinas.sj.ifsc.edu.br #Maquina do professor
  roles:
    - epoptes_server
    - ingressa_ldap

# Windows

- hosts: cad2_win
  roles:
    - programas_padroes_labs
    - config_padrao_labs
    - papel_de_parede_e_icones
    - windows_update

- hosts: sj-cad2-38841.maquinas.sj.ifsc.edu.br #Maquina do professor
  roles:
    - ingressa_ldap