#Linux

- hosts: cad3_lin
  ignore_unreachable: true
  roles:
    - role: grub
      tipo: grub_win
  tasks:
  - name: Monta /dev/sda3 em /media/aluno/trabalhos fstab - Linux
    mount:
      path: /media/aluno/trabalhos
      src: /dev/sda3
      fstype: vfat
      opts: uid=aluno,gid=aluno
      state: present
    when: ansible_os_family == 'Debian'

- hosts: cad3_lin:!sj-lin-cad3-744528.maquinas.sj.ifsc.edu.br
  ignore_unreachable: true
  roles:
    - epoptes_client

- hosts: sj-lin-cad3-744528.maquinas.sj.ifsc.edu.br #Maquina do professor
  ignore_unreachable: true
  roles:
    - epoptes_server
    - ingressa_ldap
    - owncloud_client

# Windows

- hosts: sj-cad3-744528.maquinas.sj.ifsc.edu.br #Maquina do professor
  ignore_unreachable: true
  roles:
    - ingressa_ldap
