# Linux

# Chamado da aluna Jeneffer Farias Bora IFSC#2019042510000446
- hosts: labic
  tasks:
  - name: Instala pacote idle3
    apt: name={{ packages }} state=latest
    vars:
      packages:
      - idle3
    when: ansible_os_family == 'Debian'

  # Permissao para gravar na placa
  - name: Adiciona a jeneffer no grupo dialout
    user:
      name: "{{item}}"
      groups: dialout
      append: yes
    with_items:
      - jeneffer
    when: ansible_os_family == 'Debian'