- hosts: labmeios
#  ignore_unreachable: true
  roles:
    - ingressa_ldap
    - configura_monitores
    - role: grub
      tipo: grub_soh_lin
    - role: instala_impressora_cups
      install: 1
      brother: 1
