- hosts: programacao
  roles:
    - role: grub
      tipo: grub_soh_lin

- hosts: programacao:!sj-lin-prog-744523.maquinas.sj.ifsc.edu.br
  roles:
    - epoptes_client

- hosts: sj-lin-prog-744523.maquinas.sj.ifsc.edu.br #Maquina do professor
  roles:
    - epoptes_server
    - ingressa_ldap
    - configura_monitores
    - owncloud_client
