- hosts: programacao
  roles:
    - role: debops.grub
      grub_users:
        - name: 'su'
          password: 'NBLWAThUq5'
          superuser: True
      grub_default: '0'
      grub_timeout_hardware: 15
      grub_timeout_virtual: 15
      apt_install__enabled: false
      apt__enabled: false

- hosts: programacao:!sj-lin-prog-744523.maquinas.sj.ifsc.edu.br
  roles:
    - epoptes_client

- hosts: sj-lin-prog-744523.maquinas.sj.ifsc.edu.br #Maquina do professor
  roles:
    - epoptes_server
    - ingressa_ldap
    - configura_monitores
