# Linux
- hosts: sidi_lin
#  ignore_unreachable: true
  roles:
    - role: grub
      tipo: grub_lin
  tasks:
  - name: Monta /dev/sda3 em /media/aluno/trabalhos fstab - Linux
    mount:
      path: /media/aluno/trabalhos
      src: /dev/sda3
      fstype: vfat
      state: present
    when: ansible_os_family == 'Debian'

- hosts: sidi_lin:!sj-lin-sidi-703872.maquinas.sj.ifsc.edu.br
#  ignore_unreachable: true
  roles:
    - epoptes_client

- hosts: sj-lin-sidi-703872.maquinas.sj.ifsc.edu.br #Maquina do professor
#  ignore_unreachable: true
  roles:
    - epoptes_server
    - ingressa_ldap
    - configura_monitores
    - owncloud_client

# Windows

- hosts: sj-sidi-703872.maquinas.sj.ifsc.edu.br #Maquina do professor
#  ignore_unreachable: true
  roles:
    - ingressa_ldap
