- hosts: ledis
#  ignore_unreachable: true
  roles:
    - role: grub
      tipo: grub_win

- hosts: ledis_win
  roles:
    - sam

- hosts: sj-ledis-744515.maquinas.sj.ifsc.edu.br
  roles:
    - energyplus
