---
- hosts: all
  tasks:
    - name: Instalar o aptitude, necessario para o modulo apt
      apt: name=aptitude state=latest
      when: ansible_os_family == 'Debian'
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400
      when: ansible_os_family == 'Debian'
    - name: Remove useless packages from the cache
      apt: autoclean=yes
      when: ansible_os_family == 'Debian'
    - name: Remove dependencies that are no longer required
      apt: autoremove=yes
      when: ansible_os_family == 'Debian'
    - name: Upgrade all packages to the latest version
      apt: name="*" state=latest
      when: ansible_os_family == 'Debian'
    - name: Instalar o apt-transport-https
      apt: name=apt-transport-https state=latest
      when: ansible_os_family == 'Debian'

# Administrativos
- import_playbook: comum_administrativo.yml
- import_playbook: registro_academico.yml
- import_playbook: secretaria.yml
- import_playbook: labfisica.yml
- import_playbook: cotel.yml
- import_playbook: mtele.yml
- import_playbook: des2.yml
- import_playbook: coger.yml
#- import_playbook: testes.yml
- import_playbook: ctic.yml

# Laboratorios
- import_playbook: comum_laboratorios.yml
- import_playbook: labprogramacao.yml

- hosts: all
  gather_facts: false
  tasks:
    - meta: clear_host_errors
