- hosts: mtele
  roles:
    - packettracer
    - kile
    - programas_padroes_labs

- hosts: sj-lin-mtele-38105.maquinas.sj.ifsc.edu.br
  roles:
    - zoiper
  tasks:
    - name: Adiciona usuaria mayara.sousa no grupo sudo
      user:
        name: mayara.sousa
        groups: sudo
        append: yes
      when: ansible_os_family == 'Debian'