---
- hosts: all
  gather_facts: false
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400

- include: comum_administrativo_lin.yml 
- include: testes.yml 
- include: registro_academico.yml

- hosts: all
  gather_facts: false
  tasks:
    - meta: clear_host_errors



    
