---
- hosts: teste
  tasks:
    - meta: clear_host_errors
  roles:
    - acesso_remoto
    #- banco_brasil

    - role: geerlingguy.ntp
      ntp_timezone: Etc/UTC
      ntp_manage_config: true
      ntp_servers:
        - "pool.ntp.br iburst"
        - "ntp.cais.rnp.br iburst"
        - "ntp.ufsc.br iburst"

    - role: tersmitten.apt
      apt_manage_sources_list: true
      apt_debian_mirror: http://debian.pop-sc.rnp.br/debian
      apt_debian_contrib_nonfree_enable: true
      apt_dpkg_configure: true
      apt_install: [curl, pinta]
      apt_remove: transmission-gtk
