---
- hosts: sj-lin-ricardo.maquinas.sj.ifsc.edu.br
  roles:
  - r

- hosts: sj-win-ricardo.maquinas.sj.ifsc.edu.br
  roles:
  - bricscad

- hosts: sj-lin-ctic-humberto-vm.maquinas.sj.ifsc.edu.br
  roles:
  - octave

- hosts: sj-lin-deb9lab-123.maquinas.sj.ifsc.edu.br
  roles:
  - epoptes_server
  - quadro_interativo

- hosts: sj-lin-lab-123456.maquinas.sj.ifsc.edu.br
  roles:
  - octave
