---
- hosts: testelin
  roles:
    - foxit
    - irpf

- hosts: administrativos_win
  roles:
    - programas_padroes
    - foxit
#    - irpf
    - acesso_remoto
  tasks:
    - name: Configura servidores NTP para o Windows
      win_shell: net start w32time ;	w32tm /config /manualpeerlist:"a.st1.ntp.br b.st1.ntp.br c.st1.ntp.br gps.ntp.br" /syncfromflags:manual /reliable:YES /update ; net stop w32time ; net start w32time ; w32tm /config /update ; w32tm /resync ; w32tm /resync ; New-Item c:\gatilho_ntp.txt -type file
      args:
        creates: C:\gatilho_ntp.txt


