---
- hosts: sj-lin-ricardo.maquinas.sj.ifsc.edu.br
  roles:
  - auto_desligamento

- hosts: sj-win-ricardo.maquinas.sj.ifsc.edu.br
  roles:
  - auto_desligamento

- hosts: sj-lin-ctic-humberto-vm.maquinas.sj.ifsc.edu.br
  roles:
  - cmaptools

- hosts: sj-lin-ctic-humberto-mate.maquinas.sj.ifsc.edu.br
  roles:
  - cmaptools
  
- hosts: sj-lin-deb9lab-123.maquinas.sj.ifsc.edu.br
  roles:
  - cmaptools

- hosts: sj-lin-lab-123456.maquinas.sj.ifsc.edu.br
  roles:
  - geogebra

- hosts: sj-labwin7-12345.maquinas.sj.ifsc.edu.br
  roles:
  - bricscad
