---
## Atualização demora aproximadamente 50 minutos para apenas uma maquina
- hosts: all
  tasks:
    - name: Atualiza todos os pacotes para a ultima versao
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force: yes
    - name: Alterando o sourcelist para a nova versao
      replace:
        path: '/etc/apt/sources.list'
        regexp: '(?i)stretch'
        replace: 'buster'
    - name: Realizando a atualizacao da distribuicao do SO - aguarde aguns instantes...
      apt:
        update_cache: yes
        upgrade: dist
        force: yes
