- hosts: imagens_adm_lin
  tasks:
  - name: Instalar os pacotes para o Ansible - Linux Debian
    apt: name=ansible state=latest
  - name: Pacotes padrao
    apt: name={{ packages }} state=latest
    vars:
      packages:
      - nfs-common
      - vim
      - curl
      - ethtool
      - git
      - tcpdump
      - usbutils
      - sshfs
      - net-tools
      - unzip
      - dnsutils
      - ipcalc
      - etherwake
  roles:
    - wol
    - role: grub
      tipo: grub_soh_lin
