- name: Instalar pacotes necessarios para autenticação LDAP
  apt: name={{item}} state=latest
  with_items:
    - libnss-ldap
    - libpam-ldap
    - ldap-utils
    - libpam-mount
    - cifs-utils
  when: ansible_distribution == 'Debian'
  
- name: Copiando arquivo /etc/ldap.conf
  copy:
    src: ldap.conf
    dest: /etc/ldap.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Copiando arquivo /etc/libnss-ldap.conf
  copy:
    src: ldap.conf
    dest: /etc/libnss-ldap.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Copiando arquivo /etc/pam_ldap.conf
  copy:
    src: ldap.conf
    dest: /etc/pam_ldap.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Copiando arquivo /etc/pam.d/common-auth
  copy:
    src: common-auth
    dest: /etc/pam.d/common-auth
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Copiando arquivo /etc/pam.d/common-session
  copy:
    src: common-session
    dest: /etc/pam.d/common-session
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Copiando arquivo /etc/nsswitch.conf
  copy:
    src: nsswitch.conf
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Copiando arquivo /etc/security/pam_mount.conf.xml
  copy:
    src: pam_mount.conf.xml
    dest: /etc/security/pam_mount.conf.xml
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'