#Linux
- name: Verifica versao do rambox
  shell: GET https://api.github.com/repos/ramboxapp/community-edition/tags |grep name |cut -d'"' -f4 -s
  register: versao_rambox
  changed_when: False
  when: ansible_os_family == 'Debian'
  ## Exemplo de outro jeito curl -Ls -o /dev/null -w %{url_effective} "https://github.com/rambox/community-edition/releases/latest" | grep -oE "[^/]+$"

- name: Install a .deb Rambox {{ versao_rambox.stdout }} - Linux
  apt:
    deb: https://github.com/ramboxapp/community-edition/releases/download/{{ versao_rambox.stdout }}/Rambox-{{ versao_rambox.stdout }}-linux-amd64.deb
  when: ansible_os_family == 'Debian'

- name: Altera permissão de um arquivo
  file:
    path: /opt/Rambox/chrome-sandbox
    mode: 04755
  when: ansible_os_family == 'Debian'

#Windows
#- name: Instalar o Rambox - Windows
#  win_chocolatey:
#    name: rambox
#  when: ansible_os_family == 'Windows'
