#Windows

- name: Baixar o instalador do Chem Draw 12 - Windows
  win_get_url:
    url: 'https://discovirtual.ifsc.edu.br/remote.php/webdav/SJE/CTIC/CambridgeSoft_ChemDraw_Ultra_12.0.msi'
    dest: 'C:\users\CambridgeSoft_ChemDraw_Ultra_12.0.msi'
    force: no
    url_username: "{{ url_username }}"
    url_password: "{{ url_password }}"
  when: ansible_os_family == 'Windows'

- name: Baixar e instalar o Chem Draw 12 - Windows
  win_package:
    path: 'C:\users\CambridgeSoft_ChemDraw_Ultra_12.0.msi'
    product_id: '{48DEAAF2-8276-4BBD-B7B6-91E454938476}'
    state: present
  when: ansible_os_family == 'Windows'

- name: Atalho para o Chem Draw 12 - Windows
  win_shortcut:
    description: Atalho para o Chem Draw 12
    src: 'C:\Program Files (x86)\CambridgeSoft\ChemOffice2010\Chem3D\Chem3D.exe'
    dest: '%Public%\Desktop\ChemDraw12.lnk'
    icon: 'C:\Program Files (x86)\CambridgeSoft\ChemOffice2010\Chem3D\Chem3D.exe,0'
    state: present
  when: ansible_os_family == 'Windows'


#### Ativação manual ####
- name: Serial do ChemDraw - Windows
  win_copy:
    src: serial.txt
    dest: C:\Program Files (x86)\CambridgeSoft\serial.txt
  when: ansible_os_family == 'Windows'