#Linux

- name: Adiciona repositório geogebra
  apt_repository:
    repo: deb http://www.geogebra.net/linux/ stable main
    state: present
    filename: geogebra
  when: ansible_os_family == 'Debian'

- name: Atualizacao de pacotes geogebra - Linux
  apt: name={{ packages }} state=latest
  vars:
    packages:
    - geogebra5
  when: ansible_os_family == 'Debian'

#Windows
- name: Baixar e instalar Geogebra - Windows
  win_chocolatey:
    name: geogebra
    # state: latest
  when: ansible_os_family == 'Windows'
