#Linux

# - name: Baixar e instalar geogebra 5 - Linux
#   apt:
#     deb: http://www.geogebra.org/download/deb.php?arch=amd64
#   when: ansible_os_family == 'Debian'

- name: Atualizacao de pacotes geogebra - Linux
  apt: name={{ packages }} state=latest
  vars:
    packages:
    - geogebra5
    #- geogebra-classic #Geogebra 6
  when: ansible_os_family == 'Debian'

#Windows
- name: Baixar e instalar Geogebra - Windows
  win_chocolatey:
    name: geogebra
    # state: latest
  when: ansible_os_family == 'Windows'
