#Linux

- name: Copia script para a maquina do professor no sidi - Linux
  copy:
    src: firewall_sidi.sh
    dest: /etc/init.d/firewall.sh
    owner: root
    group: root
    mode: 0755
  when: ( ansible_os_family == 'Debian' and  ansible_hostname is search("^sj-lin-sidi-703872") )

- name: Copia script para a maquina do professor no redes - Linux
  copy:
    src: firewall_redes.sh
    dest: /etc/init.d/firewall.sh
    owner: root
    group: root
    mode: 0755
  when: ( ansible_os_family == 'Debian' and  ansible_hostname is search("^sj-lin-redes-744530") )

- name: Copia script para a maquina do professor no prog - Linux
  copy:
    src: firewall_prog.sh
    dest: /etc/init.d/firewall.sh
    owner: root
    group: root
    mode: 0755
  when: ( ansible_os_family == 'Debian' and  ansible_hostname is search("^sj-lin-prog-744523") )

- name: Copia script para a maquina do professor no cad1 - Linux
  copy:
    src: firewall_cad1.sh
    dest: /etc/init.d/firewall.sh
    owner: root
    group: root
    mode: 0755
  when: ( ansible_os_family == 'Debian' and  ansible_hostname is search("^sj-lin-cad1-37247") )

- name: Copia script para a maquina do professor no cad2 - Linux
  copy:
    src: firewall_cad2.sh
    dest: /etc/init.d/firewall.sh
    owner: root
    group: root
    mode: 0755
  when: ( ansible_os_family == 'Debian' and  ansible_hostname is search("^sj-lin-cad2-38841") )

- name: Copia script para a maquina do professor no cad3 - Linux
  copy:
    src: firewall_cad3.sh
    dest: /etc/init.d/firewall.sh
    owner: root
    group: root
    mode: 0755
  when: ( ansible_os_family == 'Debian' and  ansible_hostname is search("^sj-lin-cad3-744528") )

- name: Copia regras para todas as maquinas - Linux
  copy:
    src: "{{ item }}"
    dest: /var
    owner: root
    group: root
    mode: 0755
  with_items:
    - block4
    - block6
    - wiki4
    - wiki6
    - libera
  when: ansible_os_family == 'Debian'
