#Linux

- name: Tarefa para adicionar iptables-restore na crontab aluno - Linux
  cron:
    name: "iptablesRestore"
    minute: "*/2"
    user: "root"
    job: "/usr/bin/find /var/iptables-saved -mmin -1 -type f -exec iptables-restore < /var/iptables-saved {} +"
    state: present
  when: ( ansible_os_family == 'Debian' and  aluno == 1 )

- name: Copia script para a maquina do professor no sidi - Linux
  file:
    src: firewall_sidi.sh
    dest: /etc/init.d/firewall.sh
    owner: root
    group: root
    mode: "a+x"
  when: ( ansible_os_family == 'Debian' and  ansible_hostname is search("^sj-lin-sidi") and prof == 1 )

- name: Copia script para a maquina do professor no redes - Linux
  file:
    src: firewall_redes.sh
    dest: /etc/init.d/firewall.sh
    owner: root
    group: root
    mode: "a+x"
  when: ( ansible_os_family == 'Debian' and  ansible_hostname is search("^sj-lin-redes") and prof == 1 )

- name: Copia script para a maquina do professor no prog - Linux
  file:
    src: firewall_prog.sh
    dest: /etc/init.d/firewall.sh
    owner: root
    group: root
    mode: "a+x"
  when: ( ansible_os_family == 'Debian' and  ansible_hostname is search("^sj-lin-prog") and prof == 1 )
