#Linux

- name: Copia script para a maquina do professor - Linux
  copy:
    src: firewall.sh
    dest: /etc/init.d/firewall.sh
    owner: root
    group: root
    mode: 0755
  with_items:
    - sidi-703872
    - redes-744530
    - prog-744523
    - cad1-37247
    - cad2-38841
    - cad3-744528
  when: ( ansible_os_family == 'Debian' and  ansible_hostname is search("^sj-lin-{{ item }}") )

- name: Copia o arquivo com os patrimonios para a maquina do professor - Linux
  copy:
    src: pat
    dest: /var/pat
    owner: root
    group: root
    mode: 0755
  with_items:
    - sidi-703872
    - redes-744530
    - prog-744523
    - cad1-37247
    - cad2-38841
    - cad3-744528
  when: ( ansible_os_family == 'Debian' and  ansible_hostname is search("^sj-lin-{{ item }}") )

- name: Copia regras para todas as maquinas - Linux
  copy:
    src: "{{ item }}"
    dest: /var
    owner: root
    group: root
    mode: 0755
  with_items:
    - block4
    - block6
    - wiki4
    - wiki6
    - libera
  when: ansible_os_family == 'Debian'
