#Antes de atualizar, verificar se o Ansible já gerencia snap

- name: Cria diretório jetbrains e apps
  file:
    path: /opt/jetbrains/apps
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes

- name: Baixando e extraindo o Idea jetbrains - Linux Debian
  unarchive:
    src: https://discovirtual.ifsc.edu.br/index.php/s/ArffLHA4jEM2H9C/download
    dest: /opt/jetbrains/apps
    creates: /opt/jetbrains/apps/IDEA-U/ch-0
    remote_src: yes
    owner: aluno
    group: 513
  when: ansible_os_family == 'Debian'

- name: Criando o arquivo jetbrains-idea.desktop - Linux Debian
  copy:
    src: jetbrains-idea.desktop
    dest: /usr/share/applications/jetbrains-idea.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Corrige permissões
  file:
    path: /opt/jetbrains/apps/IDEA-U
    state: directory
    owner: aluno
    group: 513
    mode: 0775
    recurse: yes