---
#Windows

- name: Cria a pasta C:\instaladores\ - Windows
  win_file:
    path: C:\instaladores\
    state: directory
  when: ansible_os_family == 'Windows'

- name: Copia o arquivo de configuracao do ISP - Windows
  win_copy:
    src: ISP.zip
    dest: C:\instaladores\ISP.zip
  when: ansible_os_family == 'Windows'

- name: Extrai o ISP em C:\Program Files\
  win_unzip:
    src: C:\instaladores\ISP.zip
    dest: C:\Program Files\
    creates: C:\Program Files\ISP
  when: ansible_os_family == 'Windows'