---
#Linux

# Debian e Ubuntu
- name: Adicionar a chave do repositório do vscode - Linux
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: ansible_os_family == 'Debian'

- name: Adicionar repositório do vscode - Linux
  apt_repository:
    filename: vscode
    repo: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Instalar o vscode - Linux
  apt:
    name: code
    state: latest
  when: ansible_os_family == 'Debian'

- name: Remove source list duplicado do code
  file:
    path: /etc/apt/sources.list.d/packages_microsoft_com_repos_vscode.list
    state: absent
  when: ansible_os_family == 'Debian'

# - name: Extraindo extensões para o vscode para lab- Linux Debian
#   unarchive:
#     src: vscode.bz
#     dest: /opt
#     owner: aluno
#     group: aluno
#     mode: 0755
#   when: ( ansible_os_family == 'Debian' and  lab == 1 )

#Windows
- name: Instalar o Visual Studio Code - Windows
  win_chocolatey:
    name: vscode
#     state: latest
  when: ansible_os_family == 'Windows'

- name: Copia as extensoes do code - Windows
  win_copy:
    src: "{{ vcode_files }}"
    dest: C:\instaladores\
  loop:
    - platformio-platformio.zip
    - vscode-cpptools.zip
    - platformio.zip
  loop_control:
    loop_var: vcode_files
  when: ansible_os_family == 'Windows'

- name: Extraindo extensão platformio e c++ para o vscode - Windows
  win_unzip:
    src: C:\instaladores\{{ vcode_extensions }}
    dest: C:\Users\aluno\.vscode\extensions
    creates: C:\Users\aluno\.vscode\extensions\platformio.platformio-ide-1.10.0
  loop:
    - vscode-cpptools.zip
    - platformio-platformio.zip
  loop_control:
    loop_var: vcode_extensions
  when: ansible_os_family == 'Windows'

- name: Extraindo configuração platformio para o vscode - Windows
  win_unzip:
    src: C:\instaladores\platformio.zip
    dest: C:\Users\aluno\
    creates: C:\Users\aluno\.platformio
  when: ansible_os_family == 'Windows'
