# Linux

# Antes de atualizar o MAC, precisa reiniciar as máquinas para confirmar que o /home/aluno estão limpos.

  - name: Atualiza o MAC das VMs
    shell: "/bin/su -c '/usr/bin/VBoxManage modifyvm {{ item }} --macaddress1 auto --macaddress2 auto' aluno"
    with_items:
      - 1-Grafico
      - 2-Grafico
      - 3-Grafico
      - 4-Grafico
      - 5-Grafico
      - 6-Grafico
      - 1-Servidor
      - 2-Servidor
      - 3-Servidor
      - 4-Servidor
      - 5-Servidor
      - 6-Servidor
      - 7-Servidor
      # - 8-Servidor
      # - 9-Servidor
      # - 10-Servidor
    when: ansible_os_family == 'Debian'

  - name: Faz backup do último aluno.tgz e cria um novo com o MAC atualizado
    shell: /bin/mv /home/backup/aluno.tgz /home/backup/aluno-$(date +'%d-%m-%Y').tgz ; /bin/tar -zcvf /home/backup/aluno.tgz /home/aluno
    when: ansible_os_family == 'Debian' and  play == 1
