- name: Instala epoptes
  apt: name=epoptes state=latest
  when: ansible_distribution == 'Debian'

- name: Remove epoptes-client
  apt: name=epoptes-client state=absent purge=yes
  when: ansible_distribution == 'Debian'

- name: Deleta o grupo epoptes local
  lineinfile:
    path: /etc/group
    state: absent
    regexp: '^epoptes'
  when: ansible_distribution == 'Debian'