- name: Instala epoptes
  apt: name=epoptes state=latest
  when: ansible_distribution == 'Debian'

- name: Remove epoptes-client
  apt: name=epoptes-client state=absent purge=yes
  when: ansible_distribution == 'Debian'

- name: Criar o grupo epoptes no arquivo /etc/group - Linux
  lineinfile:
    regexp: '^epoptes'
    path: /etc/group
    line: 'epoptes:x:900:gabriel.souza,humbertos,ctic,etorresini,odilson,moecke'
  when: ansible_os_family == 'Debian'