- name: Instala epoptes
  apt: name=epoptes state=latest
  when: ansible_os_family == 'Debian'

- name: Remove epoptes-client
  apt: name=epoptes-client state=absent purge=yes
  when: ansible_os_family == 'Debian'