#Windows

- name: Baixar o instalador do SAM
  win_get_url:
    url: 'https://discovirtual.ifsc.edu.br/index.php/s/f9ntED2i8RfgxDJ/download'
    dest: 'C:\users\sam-windows-2018-11-11-r3.exe'
    force: no
    url_username: "{{ url_username }}"
    url_password: "{{ url_password }}"
    timeout: 120
  when: ansible_os_family == 'Windows'

- name: Instalar o SAM - Windows
  win_package:
    path: 'C:\users\sam-windows-2018-11-11-r3.exe'
    arguments: '/VERYSILENT /SUPRESSMSGBOXES /NORESTART /SP-'
    product_id: '{4A0EDADE-6CE6-4CB4-907E-1401911B4D6D}_is1'
    state: present
  when: ansible_os_family == 'Windows'

### Comando em powershell para mostrar product_id
### get-wmiobject Win32_Product | Format-Table IdentifyingNumber, Name, LocalPackage -AutoSize
### Localizacao do productid 32 bits: HKLM:Software\Microsoft\Windows\CurrentVersion\Uninstall
### Localizacao do productid 64 bits: HKLM:Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall

- name: Atalho para o SAM - Windows
  win_shortcut:
    description: Atalho para o SAM
    src: 'C:\SAM\2018.11.11\x64\sam.exe'
    dest: '%Public%\Desktop\SAM.lnk'
    icon: 'C:\SAM\2018.11.11\x64\sam.exe,0'
    state: present
  when: ansible_os_family == 'Windows'
