

#Linux

- name: Copia audit_linux.sh
  copy:
    src: audit_linux.sh
    dest: /etc/init.d/audit_linux.sh
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'

- name: Tarefa que executa audit_linux.sh as 11, 17 e 21 horas - Linux
  cron:
    name: "audit_linux.sh"
    minute: "00"
    hour: "11,17,21"
    user: "root"
    job: "/etc/init.d/audit_linux.sh"
    state: present
  when: ansible_os_family == 'Debian'

#Windows

- name: Copia audit_windows.vbs - Windows
  win_copy:
    src: audit_windows.vbs
    dest: C:\audit_windows.vbs
  when: ansible_os_family == 'Windows'

- name: Tarefa que executa audit_windows.vbs após 5min depois de ligada - Windows
  win_scheduled_task:
    name: openaudit
    description: Executa a auditoria uma vez por dia
    actions:
    - path: cmd.exe
      arguments: /c c:\audit_windows.vbs
    triggers:
    - type: boot
      delay: PT5M
    username: SYSTEM
    state: present
    enabled: yes
  when: ansible_os_family == 'Windows'