#Windows

- name: Baixar o instalador do Bricscad
  win_get_url:
    url: 'https://discovirtual.ifsc.edu.br/remote.php/webdav/SJE/CTIC/BricsCAD-V18.2.20-1-pt_BR(x64).msi'
    dest: 'C:\users\BricsCAD-V18.2.20-1-pt_BR(x64).msi'
    force: no
    url_username: "{{ url_username }}"
    url_password: "{{ url_password }}"

- name: Baixar e instalar o BricsCAD - Windows
  win_package:
    path: 'C:\users\BricsCAD-V18.2.20-1-pt_BR(x64).msi'
    arguments: 'BRXLICENSESERVER="dko" SHOWRELEASENOTES=""'
    product_id: '{0A1EBB09-ADAB-4E6B-9185-54D12E8FBE56}'
    state: present
  when: ansible_os_family == 'Windows'
