---
- name: Instalar pacotes padroes
  apt: name={{item}} state=latest
  with_items:
    - aptitude 
    - vim 
    - firmware-linux 
    - vlc 
    - unrar 
    - dkms 
    - ntp 
    - libcurl3 
    - ssh 
    - pdfsam 
    - ttf-mscorefonts-installer 
    - dia 
    - kolourpaint4 
    - kdenlive
    - kde-l10n-ptbr  
    - chromium  
    - chromium-l10n 
    - browser-plugin-freshplayer-pepperflash

- name: Adicionar a chave do repositório do owncloud-client
  apt_key:
    url: https://download.opensuse.org/repositories/isv:ownCloud:desktop/Debian_9.0/Release.key
    state: present

- name: Adicionar repositório owncloud
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0/ /
    state: present
    update_cache: yes
    
- name: Instalar o Owncloud Client
  apt:
    name: owncloud-client
    state: latest
