---
- name: Instalar pacotes padroes
  apt: name={{item}} state=latest
  with_items:
    - aptitude 
    - vim 
    - firmware-linux 
    - vlc 
    - unrar 
    - dkms 
    - ntp 
    - libcurl3 
    - ssh 
    - pdfsam 
    - ttf-mscorefonts-installer 
    - dia 
    - kolourpaint4 
    - kdenlive
    - kde-l10n-ptbr  
    - chromium  
    - chromium-l10n 
    - browser-plugin-freshplayer-pepperflash

- include_role:
    name: owncloud_client
