---
#Linux
- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: pgp.mit.edu
    id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
  when: ansible_os_family == 'Debian'
# Debian 9
- name: Adicionar repositório Dropbox - Linux Debian 9
  apt_repository:
    repo: deb [arch=i386,amd64] http://linux.dropbox.com/debian stretch main
    state: present
    update_cache: yes
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'stretch')

# Debian 10
- name: Adicionar repositório Dropbox - Linux Debian 10
  apt_repository:
    repo: 'deb [arch=i386,amd64] http://linux.dropbox.com/debian buster main'
    state: present
    update_cache: yes
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'buster')

# Ubuntu
- name: Adicionar repositório dropbox - Linux Ubuntu
  apt_repository:
    repo: deb [arch=i386,amd64] http://linux.dropbox.com/debian trusty main
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

#Debian e Ubuntu
- name: Instalar o Owncloud Client - Linux Debian
  apt:
    name: dropbox
    state: latest
  when: ansible_os_family == 'Debian'

#Windows
- name: Install Dropbox - Windows
  win_chocolatey:
    name: dropbox
    # state: latest
  when: ansible_os_family == 'Windows'
