---
# Linux

- name: Baixar e instalar Teamviewer - Linux
  apt:
    deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
  when: ansible_os_family == 'Debian'

# Windows
# - name: Instalar o Teamviewer - Windows
#   win_chocolatey:
#     name: teamviewer
# #     state: latest
#   when: ansible_os_family == 'Windows'