# Somente Linux

- name: Instala o pacotes necessarios para o netkit2 - Linux
  apt: name={{ packages }} state=latest
  vars:
    packages:
    - graphviz
    - python-vte
    - bridge-utils
    - uml-utilities
    - libc6-i386
  when: ansible_distribution == 'Debian'

- name: Cria diretorio para extrair o netkit2 - Linux
  file:
    path: /usr/local/netkit2
    state: directory
    owner: root
    group: root
    mode: 01777
    recurse: no
  when: ansible_os_family == 'Debian'

- name: Baixando e extraindo o Netkit2 - Linux
  unarchive:
    src: https://discovirtual.ifsc.edu.br/index.php/s/rx9CfeNckhyzUq0/download
    dest: /usr/local/netkit2
    creates: /usr/local/netkit2/netkit-version.txt
    remote_src: yes
    owner: root
    group: root
    mode: 01777
  when: ansible_os_family == 'Debian'
  
- name: Criando o arquivo netkit2.desktop - Linux
  copy:
    src: netkit2.desktop
    dest: /usr/share/applications/netkit2.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Criando o arquivo /etc/sudoers.d/netkit2 - Linux
  copy:
    src: netkit2
    dest: /etc/sudoers.d/netkit2
    owner: root
    group: root
    mode: 0440
  when: ansible_os_family == 'Debian'

- name: Adicionar entrada no /usr/local/netkit2/bin/netkit2  - Linux
  lineinfile:
    regexp: "^  Check_Host.*$"
    state: present
    path: /usr/local/netkit2/bin/netkit2
    line: "  Check_Host = 'tele.sj.ifsc.edu.br'"
  when: ansible_os_family == 'Debian'

# Descomentar para gerar a imagem (tar home aluno)

# - name: Criando o arquivo .xsessionrc - Linux
#   copy:
#     src: .xsessionrc
#     dest: /home/aluno/.xsessionrc
#     owner: root
#     group: root
#     mode: 0755
#   when: ansible_os_family == 'Debian'

- name: Adicionar entrada NETKIT2_HOME export no /etc/security/pam_env.conf - Linux
  lineinfile:
    regexp: '^NETKIT2_HOME'
    path: /etc/security/pam_env.conf
    line: 'NETKIT2_HOME     DEFAULT=/usr/local/netkit2'
  when: ansible_os_family == 'Debian'

- name: Adicionar entrada PATH export no /etc/security/pam_env.conf - Linux
  lineinfile:
    regexp: '^PATH'
    path: /etc/security/pam_env.conf
    line: 'PATH     DEFAULT=$PATH:$NETKIT2_HOME/bin'
  when: ansible_os_family == 'Debian'

- name: Criando o arquivo .xsessionrc - Linux
  copy:
    src: .xsessionrc
    dest: /etc/skel/.xsessionrc
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'