---
- name: Adicionar repositório remmina
  apt_repository:
    repo: deb http://ftp.debian.org/debian stretch-backports main
    state: present
    update_cache: yes
    
- name: Instalar pacotes necessarios para o remmina
  apt: name={{item}} state=latest default_release=stretch-backports
  with_items:
    - remmina 
    - remmina-plugin-rdp
    - remmina-plugin-secret
    - libfreerdp-plugins-standard


# Cria o diretório softwares_remotos se não existe
- file:
    path: /var/softwares_remotos
    state: directory
    mode: 0777

- name: Copiando os arquivos remmina
  copy:
    src: remmina/{{ item }}.remmina
    dest: /var/softwares_remotos/{{  }}.remmina
    owner: root
    group: root
    mode: 0777
  with_items: "{{apps}}"

- name: Copiando os arquivos desktop
  copy:
    src: desktop/{{ item }}.desktop
    dest: /var/softwares_remotos/{{  }}.desktop
    owner: root
    group: root
    mode: 0777
  with_items: "{{apps}}"

# Copiado os icones

- name: Copiando os icones jpeg
  copy:
    src: icon/{{ item }}_icon.jpeg
    dest: /var/softwares_remotos/{{ item }}_icon.jpeg
    owner: root
    group: root
    mode: 644
  with_items: "{{apps}}"

- name: Copiando os icones ico
  copy:
    src:  icon/{{ item }}_icon.ico
    dest: /var/softwares_remotos/{{ item }}_icon.ico
    owner: root
    group: root
    mode: 644
  with_items: "{{apps}}"

- name: Copiando os icones png
  copy:
    src:  icon/{{ item }}_icon.png
    dest: /var/softwares_remotos/{{ item }}_icon.png
    owner: root
    group: root
    mode: 644
  with_items: "{{apps}}"