---
#Linux

- name: Alterar  tempo de retry do dhcp - Linux
  copy:
    src: dhclient.conf
    dest: /etc/dhcp/dhclient.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'