---
#Linux

- name: Alterar tempo de retry do dhcp no adm- Linux
  copy:
    src: dhclient.conf
    dest: /etc/dhcp/dhclient.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Inclui o role do NTP do Linux
  include_role:
    name: geerlingguy.ntp
  vars:
    ntp_timezone: America/Sao_Paulo
    ntp_manage_config: true
    ntp_servers:
      - "pool.ntp.br iburst"
      - "ntp.cais.rnp.br iburst"
      - "ntp.ufsc.br iburst"
  when: ansible_os_family == 'Debian'

##################### Inicio configuracao interfaces
- name: Mantem o estado do arquivo /etc/network/interfaces - Linux
  copy:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'
##################### Fim configuracao interfaces

##################### Copia script para procurar termos em arquivo odt
- name: Copia pesquisaodt - Linux
  copy:
    src: pesquisaODT
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'
##################### Fim configuracao interfaces

- include_role:
    name: openaudit

#Windows

- name: Configura servidor NTP para o Windows 1
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DateTime\Servers
    name: 1
    data: gps.ntp.br
  when: ansible_os_family == 'Windows'

- name: Configura servidor NTP para o Windows 2
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DateTime\Servers
    name: 2
    data: a.st1.ntp.br
  when: ansible_os_family == 'Windows'

- name: Configuracao no registro necessaria para UTC - Windows
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\TimeZoneInformation
    name: RealTimeIsUniversal
    data: 1
    type: dword
  when: ansible_os_family == 'Windows'

- name: Setar timezone no Windows
  win_timezone:
    timezone: E. South America Standard Time
  when: ansible_os_family == 'Windows'
