---
#Linux

- name: Alterar tempo de retry do dhcp no adm- Linux
  copy:
    src: dhclient.conf
    dest: /etc/dhcp/dhclient.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Inclui o role do NTP do Linux
  include_role:
    name: geerlingguy.ntp
  vars:
    ntp_timezone: America/Sao_Paulo
    ntp_manage_config: true
    ntp_servers:
      - "pool.ntp.br iburst"
      - "ntp.cais.rnp.br iburst"
      - "ntp.ufsc.br iburst"
  when: ansible_os_family == 'Debian'

##################### Inicio configuracao interfaces
- name: Mantem o estado do arquivo /etc/network/interfaces - Linux
  copy:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'
##################### Fim configuracao interfaces

##################### Copia script para procurar termos em arquivo odt
- name: Copia pesquisaodf - Linux
  copy:
    src: pesquisaODF
    dest: /usr/local/bin/pesquisaODF
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'
##################### Fim script para procurar termos em arquivo odt

##################### Copia script para procurar termos em arquivo docx xlsx pptx
- name: Copia pesquisamsx - Linux
  copy:
    src: pesquisaMSX
    dest: /usr/local/bin/pesquisaMSX
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'
##################### Fim script para procurar termos em arquivo docx xlsx pptx

##################### Impressao hodprint
- name: Instala gtklp
  apt: name=gtklp state=latest
  when: ansible_os_family == 'Debian'

- name: Copia hodprint - Linux
  copy:
    src: hodprint
    dest: /usr/bin/hodprint
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'
##################### Fim impressao hodprint

################# Copiar Chave pub Marcelo
- name: Adicionar entrada da chave pública no /root/.ssh/authorized_keys do Marcelo - Linux
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', 'marcelo.id_rsa.pub') }}" 
  when: ansible_os_family == 'Debian'

- include_role:
    name: openaudit

#Windows

- name: Configura servidor NTP para o Windows 1
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DateTime\Servers
    name: 1
    data: gps.ntp.br
  when: ansible_os_family == 'Windows'

- name: Configura servidor NTP para o Windows 2
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DateTime\Servers
    name: 2
    data: a.st1.ntp.br
  when: ansible_os_family == 'Windows'

- name: Configuracao no registro necessaria para UTC - Windows
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\TimeZoneInformation
    name: RealTimeIsUniversal
    data: 1
    type: dword
  when: ansible_os_family == 'Windows'

- name: Setar timezone no Windows
  win_timezone:
    timezone: E. South America Standard Time
  when: ansible_os_family == 'Windows'
