---
#Linux

- name: Alterar tempo de retry do dhcp - Linux
  copy:
    src: dhclient.conf
    dest: /etc/dhcp/dhclient.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Inclui o role do NTP do Linux
  include_role:
    name: geerlingguy.ntp
  vars:
    ntp_timezone: America/Sao_Paulo
    ntp_manage_config: true
    ntp_servers:
      - "pool.ntp.br iburst"
      - "ntp.cais.rnp.br iburst"
      - "ntp.ufsc.br iburst"
  when: ansible_os_family == 'Debian'

- include_role:
    name: openaudit

#Windows

- name: Configura servidores NTP para o Windows
  win_shell: net start w32time ;	w32tm /config /manualpeerlist:"a.st1.ntp.br b.st1.ntp.br c.st1.ntp.br gps.ntp.br" /syncfromflags:manual /reliable:YES /update ; net stop w32time ; net start w32time ; w32tm /config /update ; w32tm /resync ; w32tm /resync ; New-Item c:\gatilho_ntp.txt -type file
  args:
    creates: C:\gatilho_ntp.txt
  when: ansible_os_family == 'Windows'
