#Linux

# Necessário para testes, depois vai ficar no programas_padroes_labs
- name: Instalar os pacotes default Java openjdk - Linux
  apt: name={{ packages }} state=latest
  vars:
    packages:
    - default-jdk
    - default-jre
  when: ansible_os_family == 'Debian'

- name: Adiciona apt key do r-cran
  apt_key:
    keyserver: keys.gnupg.net
    id: E19F5F87128899B192B1A2C2AD5F960A256A04AF
  when: ansible_os_family == 'Debian'

- name: Adicionar repositório r-cran - Linux Debian 9
  apt_repository:
    repo: deb https://cran-r.c3sl.ufpr.br/bin/linux/debian stretch-cran35/
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'stretch')

- name: Instalar os pacotes para o r-project - Linux
  apt: name={{ packages }} state=latest
  vars:
    packages:
    - r-base
    - r-base-dev
    - libxml2-dev
    - libatlas3-base
    # - r-cran-rjava
    - libjpeg62
  when: ansible_os_family == 'Debian'

- name: Install a .deb R-Studio - Linux
  apt:
    deb: https://download1.rstudio.org/desktop/debian9/x86_64/rstudio-1.2.1335-amd64.deb
  when: ansible_os_family == 'Debian'

# # Bibliotecas Linux
# - name: Instalar bibliotecas para o r-studio - Linux
#   apt: name={{ packages }} state=latest
#   vars:
#     packages:
#     - r-cran-gdata
#     - r-cran-gmodels
#     - r-cran-gtools
#   when: ansible_os_family == 'Debian'

- name: Baixa Biblioteca RWeka e Rwekajars - Linux
  get_url:
    url: https://cran.r-project.org/src/contrib/{{item}}
    dest: /var/{{item}}
  with_items:
    - rJava_0.9-11.tar.gz
    - RWekajars_3.9.3-1.tar.gz
    - RWeka_0.4-40.tar.gz
  when: ansible_os_family == 'Debian'

- name: Instala Biblioteca RWeka e Rwekajars - Linux
  command: /usr/bin/R CMD INSTALL /var/{{item}}
  args:
    creates: /usr/local/lib/R/site-library/RWeka
  when: ansible_os_family == 'Debian'
  with_items:
    - rJava_0.9-11.tar.gz
    - RWekajars_3.9.3-1.tar.gz
    - RWeka_0.4-40.tar.gz

#Windows
- name: Verifica versao do R
  win_shell: "(choco search R.Project | findstr R.Project).substring(10,5)"
  register: versao_R
  ignore_errors: True
  when: ansible_os_family == 'Windows'

- name: Instalar o R versao {{ versao_R.stdout |trim}} - Windows
  win_chocolatey:
    name: "{{item}}"
    state: latest
  with_items:
    - r.project
    - r.studio
  when: ansible_os_family == 'Windows'

- name: Atalho para o r-project versao {{ versao_R.stdout | trim}} - Windows
  win_shortcut:
    description: Atalho para o r-project
    src: '%ProgramFiles%\R\R-{{ versao_R.stdout |trim }}\bin\x64\Rgui.exe'
    dest: '%Public%\Desktop\R.lnk'
    icon: '%ProgramFiles%\R\R-{{ versao_R.stdout |trim }}\bin\x64\Rgui.exe,0'
    args: '--cd-to-userdocs'
    state: present
  when: ansible_os_family == 'Windows'

- name: Atalho para o RStudio - Windows
  win_shortcut:
    description: Atalho para o RStudio
    src: '%ProgramFiles%\RStudio\bin\rstudio.exe'
    dest: '%Public%\Desktop\RStudio.lnk'
    state: present
  when: ansible_os_family == 'Windows'
