---
#Linux

# Debian e Ubuntu
- name: Adicionar a chave do repositório do kubernetes - Linux
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  when: ansible_os_family == 'Debian'

- name: Adicionar repositório do kubernetes - Linux
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Instalar o kubernetes - Linux
  apt:
    name: kubectl
    state: latest
  when: ansible_os_family == 'Debian'

#Windows
# - name: Instalar o kubernetes - Windows
#   win_chocolatey:
#     name: kubernetes-cli
# #     state: latest
#   when: ansible_os_family == 'Windows'
