- name: Copy driver
  win_copy:
    src: files/printer_drivers.zip
    dest: C:\Temp\

- name: Unzip a zip file
  win_unzip:
    src: C:\Temp\printer_drivers.zip
    dest: C:\Temp

- name: Install printer driver reprografia_principal
  win_shell: |
    Set-Location -LiteralPath "C:\Temp\printer_drivers\reprografia_principal\64bit"
    PNPUtil.exe /add-driver OEMSETUP.INF /install

- name: Install printer driver reprografia_reserva
  win_shell: |
    Set-Location -LiteralPath "C:\Temp\printer_drivers\reprografia_reserva\64bit"
    PNPUtil.exe /add-driver sr0emptg.inf /install

- name: Install printer driver lexmarkmx611
  win_shell: |
    Set-Location -LiteralPath "C:\Temp\printer_drivers\lexmarkmx611"
    PNPUtil.exe /add-driver LMADWP40.inf /install

- name: Install printer driver impdirecaocolor
  win_shell: |
    Set-Location -LiteralPath "C:\Temp\printer_drivers\impdirecaocolor\64bit"
    PNPUtil.exe /add-driver st0emptg.inf /install

- name: cria porta IPP 
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Print\Providers\Internet Print Provider\Ports\http://cups:631/printers/{{ item }}
  loop: "{{ impressoras }}"

- name: cria porta IPP - Authentication
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Print\Providers\Internet Print Provider\Ports\http://cups:631/printers/{{ item }}
    name: Authentication
    data: 0
    type: dword
  loop: "{{ impressoras }}"

- name: cria porta IPP - Password
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Print\Providers\Internet Print Provider\Ports\http://cups:631/printers/{{ item }}
    name: Password
    data: 0
    type: binary
  loop: "{{ impressoras }}"

- name: cria porta IPP - UserName
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Print\Providers\Internet Print Provider\Ports\http://cups:631/printers/{{ item }}
    name: UserName
    data: 0
    type: binary
  loop: "{{ impressoras }}"

- name: Restart spooler service
  win_service:
    name: spooler
    state: restarted

- name: Create printer reprografia_principal
  win_shell: |
    Add-PrinterDriver -Name "Kyocera TASKalfa 5501i KX"
    Add-Printer -Name "reprografia_principal" -DriverName "Kyocera TASKalfa 5501i KX" -Port "http://cups:631/printers/reprografia_principal"
  
- name: Create printer reprografia_reserva
  win_shell: |
    Add-PrinterDriver -Name "SHARP MX-M363N PCL6"
    Add-Printer -Name "reprografia_reserva" -DriverName "SHARP MX-M363N PCL6" -Port "http://cups:631/printers/reprografia_reserva"

- name: Create printer ImpDirecaoColor
  win_shell: |
    Add-PrinterDriver -Name "SHARP MX-C301 PCL6"
    Add-Printer -Name "ImpDirecaoColor" -DriverName "SHARP MX-C301 PCL6" -Port "http://cups:631/printers/impdirecaocolor"

- name: Create printer ImpSecretaria
  win_shell: |
    Add-PrinterDriver -Name "Lexmark MX610 Series XL"
    Add-Printer -Name "ImpSecretaria" -DriverName "Lexmark MX610 Series XL" -Port "http://cups:631/printers/impsecretaria"