#Linux

# Debian
- name: Adicionar repositório stretch-backports para Virtualbox - Linux Debian
  apt_repository:
    repo: deb http://ftp.debian.org/debian stretch-backports main contrib non-free
    state: present
    update_cache: yes
  when: ansible_distribution == 'Debian'

- name: Instalar os pacotes para o Virtualbox do stretch-backports - Linux Debian
  apt: name={{ packages }} state=latest default_release=stretch-backports
  vars:
    packages:
    - virtualbox
    - virtualbox-dkms
    - virtualbox-ext-pack
    - virtualbox-guest-utils
    - virtualbox-guest-x11
  when: ansible_distribution == 'Debian'

# Ubuntu
- name: Instalar os pacotes para o Virtualbox do ubuntu - Linux Ubuntu
  apt: name={{ packages }} state=latest
  vars:
    packages:
    - virtualbox
    - virtualbox-dkms
    - virtualbox-ext-pack
    - virtualbox-guest-utils
    - virtualbox-guest-x11
  when: ansible_distribution == 'Ubuntu'

#Windows
# - name: Instalar o Virtualbox - Windows
#   win_chocolatey:
#     name: '{{ item }}'
# #     version: 'latest'
#     skip_scripts: yes
#     force: yes
#   with_items:
#   - vboxguestadditions.install
#   - virtualbox
#   when: ansible_os_family == 'Windows'
