---
#Linux

### Remove os pacotes em conflito do owncloud-client. Deve ser executado de forma manual.

# - name: remove o Owncloud Client - Linux Debian
#   apt:    
#     state: absent    
#     purge: yes
#     autoclean: yes
#     default_release: Debian_9.0
#     pkg:
#     - ocqt5125-libsqlite0-dev
#     - owncloud-client
#     - owncloud-client-l10n
#   when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'stretch')

- name: remove a chave do repositório do owncloud-client - Linux Debian
  apt_key:
    id: 1B07204CD71B690D409F57D24ABE1AC7557BEFF9
    state: absent
  when: ansible_os_family == 'Debian'

- name: remove repositório owncloud - Linux Debian
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0/ /
    state: absent
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Instala o Owncloud Client - Linux Debian Stretch
  apt:
    state: present
    default_release: stretch-backports
    pkg:
    - owncloud-client
    - owncloud-client-l10n
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'stretch')

- name: Instala o Owncloud Client - Linux Debian Buster
  apt:
    state: present  
    pkg:
    - owncloud-client
    - owncloud-client-l10n
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'buster')

#Windows
- name: Install owncloud-client - Windows
  win_chocolatey:
    name: owncloud-client
    # state: latest
  when: ansible_os_family == 'Windows'
