#Windows
## Codigo nao testado

- name: Verifica se Energy Plus foi instalado
  win_stat:
    path: C:\EnergyPlusV9-1-0
  register: file_result

- name: Baixa o Energy Plus
  win_get_url:
    url: https://github.com/NREL/EnergyPlus/releases/download/v9.1.0/EnergyPlus-9.1.0-08d2e308bb-Windows-x86_64.exe
    dest: C:\instaladores
  when: ansible_os_family == 'Windows' and file_result.stat.exists == False

- name: Instalar o Energy Plus - Windows
  win_package:
    path: C:/instaladores/EnergyPlus-9.1.0-08d2e308bb-Windows-x86_64.exe
    arguments: /S
    product_id: 'EnergyPlusV 9.1.0-08d2e308bb'
    state: present
  when: ansible_os_family == 'Windows' and file_result.stat.exists == False

### Comando em powershell para mostrar product_id
### get-wmiobject Win32_Product | Format-Table IdentifyingNumber, Name, LocalPackage -AutoSize

# - name: Atalho para o Energy Plus
#   win_shortcut:
#     description: Atalho para o Energy Plus
#     src: 'C:\EnergyPlusV9-1-0\PostProcess\EP-Compare\EP-Compare.exe'
#     dest: '%Public%\Desktop\EP-Compare.lnk'
#     icon: 'C:\EnergyPlusV9-1-0\PostProcess\EP-Compare\EP-Compare.exe,0'
#     state: present
#   when: ansible_os_family == 'Windows'
