- name: Adicionar repositório para instalar libssl1.0.0
  apt_repository:
    repo: deb http://security.debian.org/debian-security jessie/updates main
    state: present
    update_cache: yes
  when: (ansible_os_family == 'Debian')

- name: Instalar pacotes necessarios para o warsaw
  apt:
    state: latest
    default_release: jessie
    pkg:
      - libssl1.0.0
  when: (ansible_os_family == 'Debian')

- name: Cria o grupo scard
  group:
    name: scard
    state: present
  when: ansible_os_family == 'Debian'

- name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
  user:
    name: "{{ item }}"
    group: scard
  with_items:
      - michael.silva
      - odilane
      - judite
      - sabrinamc
  when: ansible_os_family == 'Debian'

- name: Instalar pacotes necessários - Linux
  apt:
    pkg:
    - libengine-pkcs11-openssl
    - libp11-3
    - libpcsc-perl
    - libccid
    - libpcsclite1
    - libasedrive-usb
    - opensc
    - openssl
    - libopensc-openssl
    - pcscd
    - pcsc-tools
  when: ansible_os_family == 'Debian'

- name: Instala pacotes obsoletos necessário para o token
  apt:
    deb: "https://github.com/ctic-sje-ifsc/ansible/raw/master/roles/token_gd_starsign/files/{{ item }}"
    force: yes
    allow_unauthenticated: yes
    state: present
  with_items:
    - libpng12-0_1.2.49-1+deb7u2_amd64.deb
    - libjpeg62-turbo_1.5.1-2_amd64.deb
    - libwxgtk2.8-0_2.8.12.1+dfsg2-dmo4_amd64.deb
    - libgdbm3_1.8.3-14_amd64.deb
    - libwxbase2.8-0_2.8.12.1+dfsg2-dmo4_amd64.deb
    - safesignidentityclient_3.0.77-Ubuntu_amd64.deb
  when: ansible_os_family == 'Debian'
