---

###################### Inicio Adiciona no grupo dialout

# Permissao para gravar na placa
- name: Adiciona no grupo dialout
  user:
    name: "{{item}}"
    groups: dialout
    append: yes
  with_items:
    - aluno
    - mayara.sousa 
    - arliones.hoeller
    - roberto.matos
    - elen
  when: ansible_os_family == 'Debian'

###################### Fim Adiciona no grupo dialout

###################### Inicio Solicitado pelo Mello no chamado IFSC#2018060710000808 de 07/06/18

- name: Adiciona no grupo plugdev
  user:
    name: "{{item}}"
    groups: plugdev
    append: yes
  with_items:
    - aluno
  when: ansible_os_family == 'Debian'

###################### Fim Solicitado pelo Mello no chamado

### Bau: Liberacao da porta paralela
# - name: Adiciona no grupo dialout
#   file:
#     path: /dev/parport0
#     mode: "a+rw"
#     state: file
#   when: ansible_os_family == 'Debian'

### Para resolver o problema da janela de informacao que ficava fundo amarelo com letra branca do chamado IFSC#2017082510000862
# - name: Remove arquivo Troll
#   file:
#     path: /home/aluno/.config/Trolltech.conf
#     state: absent
#   when: ansible_distribution == 'Ubuntu'

###################### Inicio limpa_windows

- name: Inclui o mudulo de limpeza do Windows
  include_role:
    name: limpa_temp_windows
  vars:
    play: 0

# play: 0 desativa
# play: 1 ativa

###################### Fim limpa_windows


###################### Inicio Gerencia sudoers aluno

- name: Adiciona e modifica entrada do usuario aluno no sudoers - Linux
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^aluno '
    line: 'aluno ALL=(ALL) NOPASSWD: SETENV: /sbin/ethtool,/home/aluno/netkit2/bin/tap.py,/sbin/iptables,/sbin/ifconfig,/usr/sbin/iptraf,/usr/sbin/tcpdump,/sbin/route,/usr/local/netkit/bin/vclean,/usr/bin/minicom,/usr/sbin/brctl,/usr/sbin/traceroute,/usr/local/netkit/bin/manage_tuntap,/usr/bin/wireshark,/sbin/iwconfig,/sbin/iwlist,/sbin/iw,/etc/init.d/firewall.sh,/usr/bin/usb-creator-gtk,/sbin/dhclient,/usr/bin/MercurioIV_Linux_1.1.0.run, /etc/init.d/isc-dhcp-server,/etc/init.d/udev'
    validate: '/usr/sbin/visudo -cf %s'
  when: ansible_os_family == 'Debian'

###################### Fim Gerencia sudoers aluno

###################### Inicio do ApagaAluno

- name: Mantem o estado do arquivo /etc/init.d/apagaAluno.sh - Linux
  copy:
    src: apagaAluno.sh
    dest: /etc/init.d/apagaAluno.sh
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'

- name: Mantem o estado do arquivo /lib/systemd/system/apagaAluno.service - Linux
  copy:
    src: apagaAluno.service
    dest: /lib/systemd/system/apagaAluno.service
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Aplica o daemon-reload e o enable no servico apagaAluno - Linux
  systemd:
    enabled: yes
    daemon_reload: yes
    name: apagaAluno 
  when: ansible_os_family == 'Debian'

###################### Fim do ApagaAluno

###################### Inicio senha_aluno

- name: Cria usuário aluno com a senha aluno
  user:
    name: aluno
    groups: vboxusers
    password: $6$B5dpvoG43l67q0sx$r0LDKV2TgNItf/kYx/76l89ZN4LhP/ksYIxp.SSVGttHoSZXLSoB6Hkg2A6y7M7aFJ8zEuauf5kS/yA/P61kN1
    append: yes
  when: ansible_os_family == 'Debian'

###################### Fim do senha_aluno

###################### Inicio do atalhos_e_icones

- name: Mantem o estado do arquivo /usr/share/applications/quartus13.0sp1.desktop - Linux
  copy:
    src: quartus13.0sp1.desktop
    dest: /usr/share/applications/quartus13.0sp1.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Mantem o estado do arquivo /usr/share/applications/matlab2012b.desktop - Linux
  copy:
    src: matlab2012b.desktop
    dest: /usr/share/applications/matlab2012b.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Mantem o estado do arquivo /usr/share/applications/matlab2015a.desktop - Linux
  copy:
    src: matlab2015a.desktop
    dest: /usr/share/applications/matlab2015a.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

# # Deixei comentado para verificar se ainda eh necessario
# - name: Adicionar entrada export no /etc/bash.bashrc- Linux
#   lineinfile:
#     regexp: '^export MGLS_LICENSE_FILE'
#     path: /etc/bash.bashrc
#     line: 'export MGLS_LICENSE_FILE=1800@vm-lan2.sj.ifsc.edu.br'
#   when: ansible_os_family == 'Debian'

# - name: Adicionar entrada export no /etc/bash.bashrcs - Linux
#   lineinfile:
#     regexp: '^export LD_LIBRARY_PATH'
#     path: /etc/bash.bashrc
#     line: 'export LD_LIBRARY_PATH=/opt/altera/13.0sp1/lib32'
#   when: ansible_os_family == 'Debian'

## Feito para resolver o chamado IFSC#2017062710000273 do Moecke:
- name: Mantem o estado do arquivo /usr/share/applications/modelsim10.1d.desktop - Linux
  copy:
    src: modelsim10.1d.desktop
    dest: /usr/share/applications/modelsim10.1d.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Mantem o estado do arquivo /usr/share/applications/modelsim.png - Linux
  copy:
    src: modelsim.png
    dest: /opt/altera/13.0sp1/modelsim_ae/modelsim.png
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

# # Deixei comentado porque a princípio já está na instalação
# - name: Cria um link do /opt/altera/13.0sp1/modelsim_ae/bin/vsim para ../vco - Linux
#   file:
#     src: ../vco
#     dest: /opt/altera/13.0sp1/modelsim_ae/bin/vsim
#     state: link
#   when: ansible_os_family == 'Debian'

- name: Cria um link do vsim no /usr/local/bin - Linux
  file:
    src: /opt/altera/13.0sp1/modelsim_ae/bin/vsim
    dest: /usr/local/bin/vsim
    state: link
  when: ansible_os_family == 'Debian'

- name: Cria um link do matlab15 no /usr/local/bin - Linux
  file:
    src: /opt/matlab/R2015a/bin/matlab
    dest: /usr/local/bin/matlab15
    state: link
  when: ansible_os_family == 'Debian'

- name: Cria um link do matlab12 no /usr/local/bin - Linux
  file:
    src: /opt/matlab/R2012b/bin/matlab
    dest: /usr/local/bin/matlab12
    state: link
  when: ansible_os_family == 'Debian'

- name: Cria um link do salve seus trabalhos aqui no home do aluno - Linux
  file:
    src: /media/aluno/trabalhos
    dest: /home/aluno/trabalhos
    owner: aluno
    group: aluno
    state: link
  when: ansible_os_family == 'Debian'

# Para solucionar problemas com Ctrl + C Ctrl + v no matlab
# Deixei comentado porque podemos modificar e deixar já no home do aluno
# - name: Mantem o estado do arquivo /home/aluno/.matlab/R2015a/matlab.prf - Linux
#   copy:
#     src: matlab.prf
#     dest: /home/aluno/.matlab/R2015a/matlab.prf
#     owner: aluno
#     group: aluno
#     mode: 0644
#   when: ansible_os_family == 'Debian'

# 	#Cria um link com as configuracoes corretas do x2goclient a pedido-chamado do Moecke
# Deixei comentado porque podemos modificar e deixar já no home do aluno
# - name: Mantem o estado do arquivo /home/aluno/.x2goclient - Linux
#   copy:
#     src: .
#     dest: /home/aluno/.x2goclient
#     owner: aluno
#     group: aluno
#     mode: 0644
#   when: ansible_os_family == 'Debian'

###################### Fim do atalhos_e_icones


###################### Inicio dos Includes

- include_role:
    name: sshd_config

# - include_role:
#     name: auto_desligamento

###################### Fim dos Includes

