---

###################### Inicio Adiciona no grupo dialout

# Permissao para gravar na placa
- name: Adiciona no grupo dialout
  user:
    name: "{{item}}"
    groups: dialout
    append: yes
  with_items:
    - aluno
    - mayara.sousa
    - arliones.hoeller
    - roberto.matos
    - elen
  when: ansible_os_family == 'Debian'

###################### Fim Adiciona no grupo dialout

###################### Inicio Solicitado pelo Mello no chamado IFSC#2018060710000808 de 07/06/18

- name: Adiciona no grupo plugdev
  user:
    name: "{{item}}"
    groups: plugdev
    append: yes
  with_items:
    - aluno
  when: ansible_os_family == 'Debian'

###################### Fim Solicitado pelo Mello no chamado

### Bau: Liberacao da porta paralela
# - name: Adiciona no grupo dialout
#   file:
#     path: /dev/parport0
#     mode: "a+rw"
#     state: file
#   when: ansible_os_family == 'Debian'

### Para resolver o problema da janela de informacao que ficava fundo amarelo com letra branca do chamado IFSC#2017082510000862
# - name: Remove arquivo Troll
#   file:
#     path: /home/aluno/.config/Trolltech.conf
#     state: absent
#   when: ansible_distribution == 'Ubuntu'

###################### Inicio limpa_windows

- name: Inclui o mudulo de limpeza do Windows
  include_role:
    name: limpa_temp_windows
  vars:
    play: 0

# play: 0 desativa
# play: 1 ativa

###################### Fim limpa_windows


###################### Inicio Gerencia sudoers aluno

- name: Adiciona e modifica entrada do usuario aluno no sudoers - Linux
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^aluno '
    line: 'aluno ALL=(ALL) NOPASSWD: SETENV: /sbin/ethtool,/usr/local/netkit2/bin/tap.py,/sbin/iptables,/sbin/ifconfig,/usr/sbin/iptraf,/usr/sbin/tcpdump,/sbin/route,/usr/local/netkit/bin/vclean,/usr/bin/minicom,/usr/sbin/brctl,/usr/sbin/traceroute,/usr/local/netkit/bin/manage_tuntap,/usr/bin/wireshark,/sbin/iwconfig,/sbin/iwlist,/sbin/iw,/etc/init.d/firewall.sh,/usr/bin/usb-creator-gtk,/sbin/dhclient,/usr/bin/MercurioIV_Linux_1.1.0.run, /etc/init.d/isc-dhcp-server,/etc/init.d/udev'
    validate: '/usr/sbin/visudo -cf %s'
  when: ansible_os_family == 'Debian'

###################### Fim Gerencia sudoers aluno

###################### Inicio do ApagaAluno

# - name: Mantem o estado do arquivo /etc/init.d/apagaAluno.sh - Linux
#   copy:
#     src: apagaAluno.sh
#     dest: /etc/init.d/apagaAluno.sh
#     owner: root
#     group: root
#     mode: 0755
#   when: ansible_os_family == 'Debian'

- name: Mantem o estado do arquivo /lib/systemd/system/apagaAluno.service - Linux
  copy:
    src: apagaAluno.service
    dest: /lib/systemd/system/apagaAluno.service
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Aplica o daemon-reload e o enable no servico apagaAluno - Linux
  systemd:
    enabled: yes
    daemon_reload: yes
    name: apagaAluno
  when: ansible_os_family == 'Debian'

###################### Fim do ApagaAluno

##################### Inicio adiciona arquitetura i386

- name: Check if i386 is enabled
  shell: dpkg --print-foreign-architectures | grep i386
  register: result_i386_check
  changed_when: result_i386_check.rc == 1
  failed_when: result_i386_check.rc > 1
  when: ansible_os_family == 'Debian'

- name: Enable i386 architecture
  command: dpkg --add-architecture i386
  when: ansible_os_family == 'Debian' and result_i386_check.rc == 1

- name: Ensure apt cache is up to date
  apt: update_cache=yes
  when: ansible_os_family == 'Debian' and result_i386_check.rc == 1

##################### Fim adiciona arquitetura i386

###################### Inicio senha_aluno

- name: Cria usuário aluno com a senha aluno
  user:
    name: aluno
    groups: vboxusers
    password: $6$B5dpvoG43l67q0sx$r0LDKV2TgNItf/kYx/76l89ZN4LhP/ksYIxp.SSVGttHoSZXLSoB6Hkg2A6y7M7aFJ8zEuauf5kS/yA/P61kN1
    append: yes
  when: ansible_os_family == 'Debian'

###################### Fim do senha_aluno

###################### Inicio do atalhos_e_icones

- name: Mantem o estado do arquivo /usr/share/applications/quartus13.0sp1.desktop - Linux
  copy:
    src: quartus13.0sp1.desktop
    dest: /usr/share/applications/quartus13.0sp1.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Mantem o estado do arquivo /usr/share/applications/matlab2012b.desktop - Linux
  copy:
    src: matlab2012b.desktop
    dest: /usr/share/applications/matlab2012b.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Mantem o estado do arquivo /usr/share/applications/matlab2015a.desktop - Linux
  copy:
    src: matlab2015a.desktop
    dest: /usr/share/applications/matlab2015a.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

# Configuracao da variavel de licenca e biblioteca lib32
- name: Adicionar entrada MGLS_LICENSE_FILE export no /etc/security/pam_env.conf - Linux
  lineinfile:
    regexp: '^MGLS_LICENSE_FILE'
    path: /etc/security/pam_env.conf
    line: 'MGLS_LICENSE_FILE   DEFAULT=1800@vm-lan2.sj.ifsc.edu.br'
  when: ansible_os_family == 'Debian'

- name: Adicionar entrada LD_LIBRARY_PATH export no /etc/security/pam_env.conf - Linux
  lineinfile:
    regexp: '^LD_LIBRARY_PATH'
    path: /etc/security/pam_env.conf
    line: 'LD_LIBRARY_PATH     DEFAULT=/opt/altera/13.0sp1/lib32'
  when: ansible_os_family == 'Debian'

- name: Adicionar entrada LM_LICENSE_FILE export no /etc/security/pam_env.conf - Linux
  lineinfile:
    regexp: '^LM_LICENSE_FILE'
    path: /etc/security/pam_env.conf
    line: 'LM_LICENSE_FILE     DEFAULT=1800@vm-lan2.sj.ifsc.edu.br'
  when: ansible_os_family == 'Debian'  

## Feito para resolver o chamado IFSC#2017062710000273 do Moecke:
- name: Mantem o estado do arquivo /usr/share/applications/modelsim10.1d.desktop - Linux
  copy:
    src: modelsim10.1d.desktop
    dest: /usr/share/applications/modelsim10.1d.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Mantem o estado do arquivo /usr/share/applications/modelsim.png - Linux
  copy:
    src: modelsim.png
    dest: /opt/altera/13.0sp1/modelsim_ae/modelsim.png
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Mantem o estado do arquivo /opt/altera/13.0sp1/modelsim_ae/vco - Linux
  copy:
    src: vco
    dest: /opt/altera/13.0sp1/modelsim_ae/vco
    owner: root
    group: root
    mode: 0555
  when: ansible_os_family == 'Debian'

- name: Cria um link do /opt/altera/13.0sp1/modelsim_ae/bin/vsim para ../vco - Linux
  file:
    src: /opt/altera/13.0sp1/modelsim_ae/vco
    dest: /opt/altera/13.0sp1/modelsim_ae/bin/vsim
    force: yes
    state: link
  when: ansible_os_family == 'Debian'

- name: Cria um link do vsim no /usr/local/bin - Linux
  file:
    src: /opt/altera/13.0sp1/modelsim_ae/bin/vsim
    dest: /usr/local/bin/vsim
    state: link
  when: ansible_os_family == 'Debian'

- name: Cria um link do matlab15 no /usr/local/bin - Linux
  file:
    src: /opt/matlab/R2015a/bin/matlab
    dest: /usr/local/bin/matlab15
    state: link
  when: ansible_os_family == 'Debian'

- name: Cria um link do matlab12 no /usr/local/bin - Linux
  file:
    src: /opt/matlab/R2012b/bin/matlab
    dest: /usr/local/bin/matlab12
    state: link
  when: ansible_os_family == 'Debian'

# - name: Cria um link do salve seus trabalhos aqui no home do aluno - Linux
#   file:
#     src: /media/aluno/trabalhos
#     dest: /home/aluno/trabalhos
#     owner: aluno
#     group: aluno
#     state: link
#   when: ansible_os_family == 'Debian'

# Para solucionar problemas com Ctrl + C Ctrl + v no matlab
# Deixei comentado porque podemos modificar e deixar já no home do aluno
# - name: Mantem o estado do arquivo /home/aluno/.matlab/R2015a/matlab.prf - Linux
#   copy:
#     src: matlab.prf
#     dest: /home/aluno/.matlab/R2015a/matlab.prf
#     owner: aluno
#     group: aluno
#     mode: 0644
#   when: ansible_os_family == 'Debian'

- name: Mantem o estado do arquivo /home/aluno/.x2goclient - Linux
  copy:
    src: sessions
    dest: /home/aluno/.x2goclient/sessions 
    owner: aluno
    group: aluno
    mode: 0644
  when: ansible_os_family == 'Debian'
  tags:
    - packages

###################### Fim do atalhos_e_icones

###################### Início do NTP do Linux

- name: Inclui o role do NTP do Linux
  include_role:
    name: geerlingguy.ntp
  vars:
    ntp_timezone: America/Sao_Paulo
    ntp_manage_config: true
    ntp_servers:
      - "pool.ntp.br iburst"
      - "ntp.cais.rnp.br iburst"
      - "ntp.ufsc.br iburst"
  when: ansible_os_family == 'Debian'

###################### Fim do NTP do Linux

###################### Correcao Bug do xpdf pe do NTP do Linux

- name: Modifica o arquivo /usr/bin/xpdf - Linux
  copy:
    src: xpdf
    dest: /usr/bin/xpdf
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'
  
###################### Fim do NTP do Linux


###################### Inicio pasta instaladores Windows
- name: Cria a pasta C:\instaladores\ - Windows
  win_file:
    path: C:\instaladores\
    state: directory
  when: ansible_os_family == 'Windows'
###################### Fim pasta instaladores Windows

###################### Inicio criacao de atalhos Windows
- name: Atalho para o D - Windows
  win_shortcut:
    description: Atalho para trabalhos
    src: 'D:\'
    dest: '%Public%\Desktop\SALVE SEUS TRABALHOS AQUI.lnk'
    icon: 'C:\Windows\system32\imageres.dll,24'
    state: present
  when: ansible_os_family == 'Windows'
  ###################### Fim criacao de atalhos Windows

###################### Início do NTP Windows
- name: Configura servidores NTP para o Windows
  win_shell: net start w32time ;	w32tm /config /manualpeerlist:"a.st1.ntp.br b.st1.ntp.br c.st1.ntp.br gps.ntp.br" /syncfromflags:manual /reliable:YES /update ; net stop w32time ; net start w32time ; w32tm /config /update ; w32tm /resync ; w32tm /resync ; New-Item c:\gatilho_ntp.txt -type file
  args:
    creates: C:\gatilho_ntp.txt
  when: ansible_os_family == 'Windows'
###################### Fim do NTP Windows

###################### Inicio dos Includes

- include_role:
    name: sshd_config

# - include_role:
#     name: auto_desligamento

- include_role:
    name: openaudit

###################### Fim dos Includes

###################### Inicio configuração SP1
- name: Cria o arquivo /etc/X11/Xsession.d/99SP1 - Linux
  copy:
    src: SP1
    dest: /etc/X11/Xsession.d/99SP1
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Cria o arquivo cat /etc/profile.d/99SP1.sh - Linux
  copy:
    src: SP1
    dest: /etc/profile.d/99SP1.sh 
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian' 

- name: Adicionar entrada export no /home/aluno/.bashrc - Linux
  lineinfile:
    regexp: '^export PS1='
    path: /home/aluno/.bashrc
    line: 'export PS1="\u: \[\e[34m\]\W\[\e[m\]\\$ "'
  when: ansible_os_family == 'Debian'
 
###################### Fim configuração SP1

###################### Inicio configuração VIM
- name: Cria o arquivo /etc/vim/vimrc - Linux
  copy:
    src: vimrc
    dest: /etc/vim/vimrc
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

###################### Fim configuração VIM

