---

###################### Inicio Adiciona no grupo dialout

# Permissao para gravar na placa
- name: Adiciona no grupo dialout
  user:
    name: "{{item}}"
    groups: dialout
    append: yes
  with_items:
    - aluno
    - mayara.sousa 
    - arliones.hoeller
    - roberto.matos
    - elen
  when: ansible_os_family == 'Debian'

###################### Fim Adiciona no grupo dialout

###################### Inicio Solicitado pelo Mello no chamado IFSC#2018060710000808 de 07/06/18

- name: Adiciona no grupo plugdev
  user:
    name: "{{item}}"
    groups: plugdev
    append: yes
  with_items:
    - aluno
  when: ansible_os_family == 'Debian'

###################### Fim Solicitado pelo Mello no chamado

### Bau: Liberacao da porta paralela
# - name: Adiciona no grupo dialout
#   file:
#     path: /dev/parport0
#     mode: "a+rw"
#     state: file
#   when: ansible_os_family == 'Debian'

### Para resolver o problema da janela de informacao que ficava fundo amarelo com letra branca do chamado IFSC#2017082510000862
# - name: Remove arquivo Troll
#   file:
#     path: /home/aluno/.config/Trolltech.conf
#     state: absent
#   when: ansible_distribution == 'Ubuntu'

###################### Inicio limpa_windows

- name: Inclui o mudulo de limpeza do Windows
  include_role:
    name: limpa_temp_windows
  vars:
    play: 0

# play: 0 desativa
# play: 1 ativa

###################### Fim limpa_windows


###################### Inicio Gerencia sudoers aluno

- name: Adiciona e modifica entrada do usuario aluno no sudoers - Linux
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^aluno '
    line: 'aluno ALL=(ALL) NOPASSWD: SETENV: /sbin/ethtool,/home/aluno/netkit2/bin/tap.py,/sbin/iptables,/sbin/ifconfig,/usr/sbin/iptraf,/usr/sbin/tcpdump,/sbin/route,/usr/local/netkit/bin/vclean,/usr/bin/minicom,/usr/sbin/brctl,/usr/sbin/traceroute,/usr/local/netkit/bin/manage_tuntap,/usr/bin/wireshark,/sbin/iwconfig,/sbin/iwlist,/sbin/iw,/etc/init.d/firewall.sh,/usr/bin/usb-creator-gtk,/sbin/dhclient,/usr/bin/MercurioIV_Linux_1.1.0.run, /etc/init.d/isc-dhcp-server,/etc/init.d/udev'
    validate: '/usr/sbin/visudo -cf %s'
  when: ansible_os_family == 'Debian'

###################### Fim Gerencia sudoers aluno

###################### Inicio do ApagaAluno

- name: Mantem o estado do arquivo /etc/init.d/apagaAluno.sh - Linux
  copy:
    src: apagaAluno.sh
    dest: /etc/init.d/apagaAluno.sh
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'

- name: Mantem o estado do arquivo /lib/systemd/system/apagaAluno.service - Linux
  copy:
    src: apagaAluno.service
    dest: /lib/systemd/system/apagaAluno.service
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Aplica o daemon-reload e o enable no servico apagaAluno - Linux
  systemd:
    enabled: yes
    daemon_reload: yes
    name: apagaAluno 
  when: ansible_os_family == 'Debian'

###################### Fim do ApagaAluno


###################### Inicio dos Includes

- include_role:
    name: sshd_config

# - include_role:
#     name: auto_desligamento

###################### Fim dos Includes

###################### Inicio senha_aluno

- name: Cria usuário aluno com a senha aluno
  user:
    name: aluno
    groups: vboxusers
    password: $6$B5dpvoG43l67q0sx$r0LDKV2TgNItf/kYx/76l89ZN4LhP/ksYIxp.SSVGttHoSZXLSoB6Hkg2A6y7M7aFJ8zEuauf5kS/yA/P61kN1
    append: yes

###################### Fim do senha_aluno