---
#Linux
- name: Instalar os pacotes necessários para o warsaw
  apt: name={{ packages }} state=latest
  vars:
    packages:
    - libnss3-tools
    - libcurl3
  when: ansible_distribution == 'Debian'

- name: Instalar o .deb warsaw - Linux Debian
  apt:
    deb: https://cloud.gastecnologia.com.br/bb/downloads/ws/warsaw_setup64.deb
  when: ansible_distribution == 'Debian'
