---
# Debian e Ubuntu
- name: Apagar disk1 antes de restaurar as máquinas virtuais - Linux
  file:
    path: /home/VMDK/{{ item }}-disk1.vmdk
    state: absent
  with_items: "{{nome_vms}}"
  when: ansible_os_family == 'Debian'

- name: Apagar disk2 antes de restaurar as máquinas virtuais - Linux
  file:
    path: /home/VMDK/{{ item }}-disk2.vmdk
    state: absent
  with_items: "{{nome_vms}}"
  when: ansible_os_family == 'Debian'

- name: Restaurar as máquinas virtuais - Linux
  unarchive:
    src: /home/backup/{{ item }}.bz
    dest: /
    remote_src: yes
  with_items: "{{nome_vms}}"
  when: ansible_os_family == 'Debian'
