---
#Linux

- name: Install a .deb Google Chrome - Linux Debian
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  when: ansible_os_family == 'Debian'

- name: Instalar pacotes padroes - Linux
  apt: name={{item}} state=latest
  with_items:
    - aptitude 
    - vim 
    - firmware-linux 
    - vlc 
    - unrar 
    - dkms 
    - ntp 
    - libcurl3 
    - ssh 
    - pdfsam 
    - ttf-mscorefonts-installer 
    - dia 
    - kolourpaint4 
    - kdenlive
    - kde-l10n-ptbr  
    - chromium  
    - chromium-l10n 
    - openjdk-8-jre
    - icedtea-8-plugin
    - google-chrome-stable
  when: ansible_os_family == 'Debian'

- name: Remover programas  - Linux
  apt: name={{item}} state=absent
  with_items:
    - transmission
    - transmission-common
  when: ansible_os_family == 'Debian'

- include_role:
    name: warsaw

#Windows
- name: Instalar pacotes padroes - Windows
  win_chocolatey: name={{ item }} state=latest
  with_items:
    - googlechrome
    - jre8
    - firefoxesr
    - 7zip
    - vlc
    - libreoffice-oldstable
    - pdfsam
    - cutepdf
    - adobereader
    - microsoftsecurityessentials 
  when: ansible_os_family == 'Windows'

#Windows e Linux
- include_role:
    name: owncloud_client

- include_role:
    name: flashplayer