---
#Linux

# Debian e Ubuntu
- name: Configuracao dos monitores para o lab sidi - Linux
  copy:
    content: |
      #!/bin/bash
      xrandr --output VIRTUAL-1 --off --output DP-2 --off --output DP-1 --off --output HDMI-2 --mode 1600x900 --pos 1600x0 --rotate normal --output HDMI-1 --primary --mode 1600x900 --pos 0x0 --rotate normal --output VGA-1 --mode 1600x900 --pos 1600x0 --rotate normal
        
    dest: /etc/X11/Xsession.d/99ConfigMonitor
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname is search("^sj-lin-sidi")

- name: Configuracao dos monitores para o lab redes - Linux
  copy:
    content: |
      #!/bin/bash
      xrandr --output VIRTUAL1 --off --output DP1 --off --output HDMI3 --off --output HDMI2 --mode 1280x1024 --primary --pos 0x0 --rotate normal --output HDMI1 --mode 1280x1024 --pos 1280x0 --rotate normal --output VGA1 --mode 1280x1024 --pos 1280x0 --rotate normal
        
    dest: /etc/X11/Xsession.d/99ConfigMonitor
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname is search("^sj-lin-redes")

- name: Configuracao dos monitores para o lab prog - Linux
  copy:
    content: |
      #!/bin/bash
      xrandr --output VIRTUAL1 --off --output DP1 --off --output HDMI3 --off --output HDMI2 --mode 1600x900 --primary --pos 0x0 --rotate normal --output HDMI1 --mode 1280x1024 --pos 1600x0 --rotate normal --output VGA1 --mode 1440x900 --pos 1600x0 --rotate normal
        
    dest: /etc/X11/Xsession.d/99ConfigMonitor
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname is search("^sj-lin-prog")  
