---
# Linux
- name: Instalar pacotes para o pc do sinal - Linux Debian
  apt:
    state: latest
    pkg:
    - gcc
    - vim
    - curl
    - ethtool
    - lm-sensors
    - tcpdump
    - nfs-common
  when: ansible_os_family == 'Debian'

- name: Cria diretorio para o sinal
  file:
    path: /opt/sinal/
    state: directory
    owner: root
    group: root
    mode: 0777
    recurse: yes
  when: ansible_os_family == 'Debian'

- name: Copiando arquivo necessario para o sinal 64bits
  copy:
    src: "s1_64"
    dest: /opt/sinal/s1
    owner: root
    group: root
    mode: 0777
  when: ( ansible_os_family == 'Debian' and ansible_userspace_bits == '64' )

- name: Copiando arquivo necessario para o sinal 32bits
  copy:
    src: "s1_32"
    dest: /opt/sinal/s1
    owner: root
    group: root
    mode: 0777
  when: ( ansible_os_family == 'Debian' and ansible_userspace_bits == '32' )

- name: Cron horario do inicio das aulas
  cron:
    name: "inicio"
    weekday: 1-5
    minute: "28,30,40"
    hour: "7,13,18"
    job: "/opt/sinal/./s1"

- name: Cron horario intervalo 1
  cron:
    name: "intervalo1"
    weekday: 1-5
    minute: "25"
    hour: "8,14,19"
    job: "/opt/sinal/./s1"

- name: Cron horario recreio
  cron:
    name: "recreio"
    weekday: 1-5
    minute: "20,40"
    hour: "9,15,20"
    job: "/opt/sinal/./s1"

- name: Cron horario intervalo 2
  cron:
    name: "intervalo2"
    weekday: 1-5
    minute: "35"
    hour: "10,16,21"
    job: "/opt/sinal/./s1"

- name: Cron horario termino das aulas
  cron:
    name: "termino"
    weekday: 1-5
    minute: "30"
    hour: "11,17,22"
    job: "/opt/sinal/./s1"
