# Ubuntu
- name: Adicionar repositório Octave - Linux Ubuntu
  apt_repository:
    repo: ppa:octave/stable
  when: ansible_distribution == 'Ubuntu'

# Debian e Ubuntu
- name: Instalar os pacotes para o octave - Linux
  apt: name={{ packages }} state=latest
  vars:
    packages:
    - octave
    - octave-communications
    - octave-control
    - octave-signal    
  when: ansible_os_family == 'Debian'