- name: Baixa e extrai astah_community
  unarchive:
    src: https://discovirtual.ifsc.edu.br/index.php/s/ibVgxuloekxnYTY/download
    dest: /opt/
    creates: /opt/astah_community
    remote_src: yes
    owner: root
    group: root
    mode: 0755  
  when: ansible_os_family == 'Debian'

- name: Criando o arquivo astah_community.desktop - Linux Debian
  copy:
    src: astah_community.desktop
    dest: /usr/share/applications/astah_community.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'