#Linux

# Debian
- name: Adicionar repositório stretch-backports para Virtualbox - Linux Debian
  apt_repository:
    repo: deb http://ftp.debian.org/debian stretch-backports main contrib non-free
    state: present
    update_cache: yes
  when: ansible_distribution == 'Debian'

# Debian
- name: Instalar os pacotes para o Virtualbox do stretch-backports - Linux Debian
  apt: name={{item}} state=latest default_release=stretch-backports
  with_items:
    - virtualbox
    - virtualbox-dkms
    - virtualbox-ext-pack
    - virtualbox-guest-utils
    - virtualbox-guest-x11
  when: ansible_distribution == 'Debian'

#Windows

- name: Instalar o R Project - Windows
  win_chocolatey:
    name: r.project
    version: '3.5.1'
  when: ansible_os_family == 'Windows'
