---
#Linux
- name: Instala wpasupplicant - Linux
  apt: name={{ packages }} state=latest
  vars:
    packages:
    - wpasupplicant
  when: ansible_os_family == 'Debian'

- name: Copiando arquivo hosts - Linux
  copy:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Copiando arquivo interfaces - Linux
  copy:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Copiando arquivo wpa_supplicant - Linux
  copy:
    src: wpa_supplicant.conf
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    owner: root
    group: root
    mode: 0600
  when: ansible_os_family == 'Debian'

- name: Cron para apagar o resolv.conf
  cron:
    name: "apaga dns"
    minute: "2"
    job: '/bin/echo "" > /etc/resolv.conf'
  when: ansible_os_family == 'Debian'
