---
#Linux

# Debian e Ubuntu    
- name: Instalar o epoptes-client - Linux
  apt: name=epoptes-client state=latest
  when: ansible_os_family == 'Debian'


- name: Adicionar entrada no /etc/hosts sobre quem é o server - Linux
  lineinfile:
    regexp: 'server$'
    path: /etc/hosts
    line: '192.168.1.1 server'
  when: ansible_hostname is search("^sj-lin-ric")

