#Linux
# - name: Verifica versao do HELM
#   shell: curl -Ls -o /dev/null -w %{url_effective} "https://github.com/helm/helm/releases/latest" | grep -oE "[^/]+$"
#   register: versao_helm
#   ignore_errors: True

- name: Install RKE version v0.2.2 - Linux
  get_url:
    url: https://github.com/rancher/rke/releases/download/v0.2.2/rke_linux-amd64
    dest: /usr/local/bin/rke
    owner: root
    group: root
    mode: 0555
    checksum: sha256:6b6c60aab8ee3135fec6af4d82a24814664b9ee5f9b283864dfbe5a5855ca15f
  when: ansible_os_family == 'Debian'

- name: Install HELM v2.14.0 - Linux
  unarchive:
    src: helm.bz
    dest: /usr/local/bin
    mode: 0555
    creates: /usr/local/bin/helm
  when: ansible_os_family == 'Debian'


#Windows
- name: Baixar o RKE version v0.2.2 - Windows
  win_get_url:
    url: 'https://storage.googleapis.com/kubernetes-helm/helm-v2.14.0-linux-amd64.tar.gz'
    dest: '/usr/local'
    force: no
    timeout: 120
  when: ansible_os_family == 'Windows'
