- hosts: agatha
  become: true
  become_method: su
  gather_facts: False
  pre_tasks:
    - name: Instala o python para o Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal python-simplejson sudo vim)
      changed_when: False
      become: true

  tasks:
  - name: Adicionar entrada da chave pública no /root/.ssh/authorized_keys (Monitoramento)
    authorized_key:
      user: root
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEArgRS9p4JBq6CGuugYkf8PW7lejJpcJzDdjntND8wKhGUibkZRXcrxI40ClDEp7xLPzIzx6YSyV77AA16ers6AZs83FVSQY/sVO/qTXReyjHKJ1UhB3NQWsMI6XO+mcHFef50WLJ4rHd6b3A8swwF4XK4UtF8K6cDtJnJ1w4DmGwf3uAec0dUWF7UF4nP9VkTbH4bWETHPO7VXy5AcXx3rkzFF6+krtvrUHvC6QlzcUT0ofqb3mLBbWstaznE/lqXRFqHVwkkSLTy476qYM5286+UOTfTcwjsVCiohpoihPGWp4UE8ROKSmP8wLdYGHEJrB9k5FJGkZ5RjLhQ9ZIW9Dn/cgqFjOpvICe+26Zc7qaKTDp9vTCVkrZ94RV1e8gWlwbWcdNavuvpKcIxaNVmsxZ3RUiI5yewdGR3PCEbRkBiKq49E9cmitgbYWnn1jTQz9XXFSXL2MxRA4df6khmPZtKukvdjljt4jfbR40CZ5Q6VtJLO4yN7oYUWE+z3+YJtalT2VYO+L12phVAwjLlwn7JXijzXckBt6mCtTmQFCLBek/Y3EGdYpKnGLCfwvenpebxUOrhZFX8RJiHH8RQqUVv9LYtCdt88RdzAG15FlHufYQQHC+t2nZDrtW+XHpLBPgLFmbfDf03OIfIg/hxPwCDSPKqWgnpWJukdmuVze8= root@monitoramento"

  - name: Adicionar entrada da chave pública no /root/.ssh/authorized_keys (Humberto)
    authorized_key:
      user: root
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYymPFCq/EpbDr9Y5az6z6s3EO1WiiHboeyB94dKSplOG6GSddtwSu4WTr+QSPNks7farRQtAsQUi4j93fVD+T6Nt8k6nWLpbtUx2DLp17rsqi67RO1QixdywwcZwdYCaBztmaZlfPHVVC/rBXeonj8uz51AgpYrQCvnOXrCNWt6m7OpYn3b+AdUC3A3gu8b2KW7cmS1pLZMctfvAbMcFd93a4qO6J8J5dX/ZGG2o/l8Tt82GLGam+3x5Jyi6qa61RxHAbjibdo0WoSrQdGh0bU8twvaTi9bbdeOqa0UVdxDWfpAZY/HBxfRnb9FSVCb+BB9sDB3eyS0CC7KajFqe5 humbertos@sj-ctic-37246"

  - name: Adicionar entrada da chave pública no /root/.ssh/authorized_keys (Gabriel)
    authorized_key:
      user: root
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxZ6W+iZn1dlWBBxLI3ZHup8LRGk4YpnynlG8Fm4oLdM/2fWKupyl8SJDity0m13AVQBMgpR2k/BA1HLFnWjPpxsjsA03ORTVFG3zGN8Yqb0LRuPfpXmQTQtVtGkN7FD4JKyzFeY+G4J0K3mVjOO2F8pGLvrota6q0/8fNfMsHt0uDZpC9c34qM6Xq72ZChJhnq4JY0QT6fzu2BmVnjDz4eBDlrsbtzdgkNF+z1jLdd4xSYgqFhUIrhU8Bsf6vGQMR0CRFh8huKaDCb4/y2F0NmIX0Y5ycwNfOHwvUoIYJMgv0bWv8Ewfg1MsEQ2MxN67H/4/zmMjo9jM7c40R7nmFwhm4pMMCpH8R7DoLAm4g1cKt80GXaef+7OBuluVcV6qOzaIMhBhOxjZomBgw/fjnUSjWrwJEHXNsAE8/gQLaM6OyMVl0L53FL1f8CuhQC618yge9DhM2yDw7IBxxteyA6Mp1GNPSx0HFFqisEZD0q7ZxW3PQMaTqM3Gdf+ONTP1tGbEirPn3YB3erqaYwirRNERcOpJqh/h9ahi8A9HLmSgOB0JGwKPS39ZBDU4OplIWhHY4QT6orzbrO/IkNXv7DxKQjt9N/kytVpP7MNgB6Mrepi4FDA2OUNKYCZ31c29SFOAUWjjd6K5r4W3JTbJtxVjME4/ifd6oQQHFdNIl2w== gabriel.souza@sj-ctic-29736"

- hosts: agatha
  vars_files:
    - vars/agatha/token_agatha_reitoria.yaml
  roles:
    - ../roles/docker

    - role: ansiblebit.oracle-java
      oracle_java_use_defaults: yes
      oracle_java_apt_repository: 'deb http://ppa.launchpad.net/webupd8team/java/ubuntu bionic main'
      oracle_java_apt_repository_key: 'EA8CACC073C3DB2A'
      oracle_java_cache_valid_time: 3600
      oracle_java_deb_package: 'oracle-java8-installer'
      oracle_java_debconf_package_default: 'oracle-java8-set-default'
      oracle_java_home: "/usr/lib/jvm/java-8-oracle"
      oracle_java_license_version: "shared/accepted-oracle-license-v1-1"
      oracle_java_set_as_default: yes
      oracle_java_state: latest

  tasks:  
  - name: Instalar pacotes necessarios para o AGATHA - Linux
    apt: name={{ packages }} state=latest
    vars:
      packages:
      - default-jdk
      - maven

  - name: Adicionar repositório stretch-backports - Linux Debian
    apt_repository:
      repo: deb http://ftp.debian.org/debian stretch-backports main contrib non-free
      state: present
      update_cache: yes
    when: ansible_distribution == 'Debian'

  - name: Instalar os pacotes do nodejs do stretch-backports - Linux Debian
    apt: name={{ packages }} state=latest default_release=stretch-backports
    vars:
      packages:
      - build-essential 
      - nodejs
      - npm
    when: ansible_distribution == 'Debian' 

  - name: Instala o docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0755

# Clona o repositório em /opt/agatha

  - git:
      repo: http://softwarepublico.gov.br/gitlab/agatha/agatha.git
      dest: /opt/agatha
      update: no

# Personalizações do arquivo /opt/agatha/docker/spring/config/application.yaml

  - lineinfile:
      path: /opt/agatha/docker/spring/config/application.yaml
      regexp: '^  client-id:'
      line: '  client-id: {{ client_id }}'

  - lineinfile:
      path: /opt/agatha/docker/spring/config/application.yaml
      regexp: '^  client-secret:'
      line: '  client-secret: {{ client_secret }}'

  - replace:
      path: /opt/agatha/docker/spring/config/application.yaml
      regexp: 'dns_definido'
      replace: 'gr.ifsc.edu.br'

  - replace:
      path: /opt/agatha/docker/spring/config/application.yaml
      regexp: '^  access-token-uri: https://testescp-ecidadao.estaleiro.serpro.gov.br/scp/token'
      replace: '  #access-token-uri: https://testescp-ecidadao.estaleiro.serpro.gov.br/scp/token'

  - replace:
      path: /opt/agatha/docker/spring/config/application.yaml
      regexp: '^  user-authorization-uri: https://testescp-ecidadao.estaleiro.serpro.gov.br/scp/authorize'
      replace: '  #user-authorization-uri: https://testescp-ecidadao.estaleiro.serpro.gov.br/scp/authorize'      

  - replace:
      path: /opt/agatha/docker/spring/config/application.yaml
      regexp: '^  validacao-uri: https://testescp-ecidadao.estaleiro.serpro.gov.br/scp/jwk'
      replace: '  #validacao-uri: https://testescp-ecidadao.estaleiro.serpro.gov.br/scp/jwk'

  - replace:
      path: /opt/agatha/docker/spring/config/application.yaml
      regexp: '#  access-token-uri: SOLICITAR-MP'
      replace: '  access-token-uri: {{ access_token_uri }}'

  - replace:
      path: /opt/agatha/docker/spring/config/application.yaml
      regexp: '#  user-authorization-uri: SOLICITAR-MP'
      replace: '  user-authorization-uri: {{ user_authorization_uri }}'
