- hosts: arquivos

  vars:
    pastas: [almoxtele, cgeaen, cgeral, cgp, coger, comaf, compras, comunicacao, contratos, corac, cotel, ctic, cursoad, dam, depe, depx, direcao, edfisica, escultura, estagios, extensao, financeiro, gabinete, geden, gtcarreira, gtmemoria, licenciatura, matematica, orcamento, pesquisa, portarias, proeja, pronatec, rac, registro, sebib, secretaria, suporteed, tele]
  
  tasks:
  - name: Adicionar entrada da chave pública no /root/.ssh/authorized_keys (Monitoramento)
    authorized_key:
      user: root
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEArgRS9p4JBq6CGuugYkf8PW7lejJpcJzDdjntND8wKhGUibkZRXcrxI40ClDEp7xLPzIzx6YSyV77AA16ers6AZs83FVSQY/sVO/qTXReyjHKJ1UhB3NQWsMI6XO+mcHFef50WLJ4rHd6b3A8swwF4XK4UtF8K6cDtJnJ1w4DmGwf3uAec0dUWF7UF4nP9VkTbH4bWETHPO7VXy5AcXx3rkzFF6+krtvrUHvC6QlzcUT0ofqb3mLBbWstaznE/lqXRFqHVwkkSLTy476qYM5286+UOTfTcwjsVCiohpoihPGWp4UE8ROKSmP8wLdYGHEJrB9k5FJGkZ5RjLhQ9ZIW9Dn/cgqFjOpvICe+26Zc7qaKTDp9vTCVkrZ94RV1e8gWlwbWcdNavuvpKcIxaNVmsxZ3RUiI5yewdGR3PCEbRkBiKq49E9cmitgbYWnn1jTQz9XXFSXL2MxRA4df6khmPZtKukvdjljt4jfbR40CZ5Q6VtJLO4yN7oYUWE+z3+YJtalT2VYO+L12phVAwjLlwn7JXijzXckBt6mCtTmQFCLBek/Y3EGdYpKnGLCfwvenpebxUOrhZFX8RJiHH8RQqUVv9LYtCdt88RdzAG15FlHufYQQHC+t2nZDrtW+XHpLBPgLFmbfDf03OIfIg/hxPwCDSPKqWgnpWJukdmuVze8= root@monitoramento"

  - name: Adicionar entrada da chave pública no /root/.ssh/authorized_keys (Humberto)
    authorized_key:
      user: root
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYymPFCq/EpbDr9Y5az6z6s3EO1WiiHboeyB94dKSplOG6GSddtwSu4WTr+QSPNks7farRQtAsQUi4j93fVD+T6Nt8k6nWLpbtUx2DLp17rsqi67RO1QixdywwcZwdYCaBztmaZlfPHVVC/rBXeonj8uz51AgpYrQCvnOXrCNWt6m7OpYn3b+AdUC3A3gu8b2KW7cmS1pLZMctfvAbMcFd93a4qO6J8J5dX/ZGG2o/l8Tt82GLGam+3x5Jyi6qa61RxHAbjibdo0WoSrQdGh0bU8twvaTi9bbdeOqa0UVdxDWfpAZY/HBxfRnb9FSVCb+BB9sDB3eyS0CC7KajFqe5 humbertos@sj-ctic-37246"

  - name: Adicionar entrada da chave pública no /root/.ssh/authorized_keys (Gabriel)
    authorized_key:
      user: root
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxZ6W+iZn1dlWBBxLI3ZHup8LRGk4YpnynlG8Fm4oLdM/2fWKupyl8SJDity0m13AVQBMgpR2k/BA1HLFnWjPpxsjsA03ORTVFG3zGN8Yqb0LRuPfpXmQTQtVtGkN7FD4JKyzFeY+G4J0K3mVjOO2F8pGLvrota6q0/8fNfMsHt0uDZpC9c34qM6Xq72ZChJhnq4JY0QT6fzu2BmVnjDz4eBDlrsbtzdgkNF+z1jLdd4xSYgqFhUIrhU8Bsf6vGQMR0CRFh8huKaDCb4/y2F0NmIX0Y5ycwNfOHwvUoIYJMgv0bWv8Ewfg1MsEQ2MxN67H/4/zmMjo9jM7c40R7nmFwhm4pMMCpH8R7DoLAm4g1cKt80GXaef+7OBuluVcV6qOzaIMhBhOxjZomBgw/fjnUSjWrwJEHXNsAE8/gQLaM6OyMVl0L53FL1f8CuhQC618yge9DhM2yDw7IBxxteyA6Mp1GNPSx0HFFqisEZD0q7ZxW3PQMaTqM3Gdf+ONTP1tGbEirPn3YB3erqaYwirRNERcOpJqh/h9ahi8A9HLmSgOB0JGwKPS39ZBDU4OplIWhHY4QT6orzbrO/IkNXv7DxKQjt9N/kytVpP7MNgB6Mrepi4FDA2OUNKYCZ31c29SFOAUWjjd6K5r4W3JTbJtxVjME4/ifd6oQQHFdNIl2w== gabriel.souza@sj-ctic-29736"

# Samba4

  - name: Instalar pacotes uteis Samba - Linux
    apt: name={{ packages }} state=latest
    vars:
      packages:
      - parted
      - quota
      - quotatool
      - xfsprogs

  # - name: cria script para quota de home
  #   copy:
  #     content: |
  #       #! /bin/bash
  #       # verificando quota: xfs_quota -x -c 'report -hu' /arquivos/home
  #       final_count=$(ls -l /arquivos/home |wc -l)
  #         for i in $(seq 1 ${final_count})
  #           do
  #             user=$(ls -w 3 /arquivos/home/ |head -n ${i} |tail -n 1)
  #             xfs_quota -x -c "limit -u bsoft=2048M bhard=2560M ${user}" /arquivos/home
  #         done
  #     dest: /root/define_quota_home.sh
  #     owner: root
  #     group: root
  #     mode: 0500

  - name: create folder to printer spool
    file:
      path: /var/spool/samba/
      state: directory
      mode: 1777
  
  - name: Set user default blocks limits on /arquivos/home 
    xfs_quota:
      type: user
      mountpoint: /arquivos/home
      bsoft: 0g
      bhard: 2.5g

  - name: create project quota file
    copy:
      content: |
        1:/arquivos/grupos/almoxtele
        2:/arquivos/grupos/cgeral
        3:/arquivos/grupos/cgp
        4:/arquivos/grupos/coger
        5:/arquivos/grupos/comaf
        6:/arquivos/grupos/compras
        7:/arquivos/grupos/comunicacao
        8:/arquivos/grupos/contratos
        9:/arquivos/grupos/corac
        10:/arquivos/grupos/cotel
        11:/arquivos/grupos/ctic
        12:/arquivos/grupos/cursoad
        13:/arquivos/grupos/dam
        14:/arquivos/grupos/depe
        15:/arquivos/grupos/depx
        16:/arquivos/grupos/direcao
        17:/arquivos/grupos/drivers
        18:/arquivos/grupos/edfisica
        19:/arquivos/grupos/escultura
        20:/arquivos/grupos/estagios
        21:/arquivos/grupos/eventos
        22:/arquivos/grupos/extensao
        23:/arquivos/grupos/financeiro
        24:/arquivos/grupos/gabinete
        25:/arquivos/grupos/geden
        26:/arquivos/grupos/gtcarreira
        27:/arquivos/grupos/gtmemoria
        28:/arquivos/grupos/licenciatura
        29:/arquivos/grupos/matematica
        30:/arquivos/grupos/orcamento
        31:/arquivos/grupos/pesquisa
        32:/arquivos/grupos/pocv
        33:/arquivos/grupos/portarias
        34:/arquivos/grupos/proeja
        35:/arquivos/grupos/pronatec
        36:/arquivos/grupos/publico
        37:/arquivos/grupos/rac
        38:/arquivos/grupos/registro
        39:/arquivos/grupos/sebib
        40:/arquivos/grupos/secretaria
        41:/arquivos/grupos/sistemas
        42:/arquivos/grupos/software
        43:/arquivos/grupos/suporteed
        44:/arquivos/grupos/tele
      dest: /etc/projects
      mode: 0600
  
  - name: create projid file
    copy:
      content: |
        almoxtele:1
        cgeral:2
        cgp:3
        coger:4
        comaf:5
        compras:6
        comunicacao:7
        contratos:8
        corac:9
        cotel:10
        ctic:11
        cursoad:12
        dam:13
        depe:14
        depx:15
        direcao:16
        drivers:17
        edfisica:18
        escultura:19
        estagios:20
        eventos:21
        extensao:22
        financeiro:23
        gabinete:24
        geden:25
        gtcarreira:26
        gtmemoria:27
        licenciatura:28
        matematica:29
        orcamento:30
        pesquisa:31
        pocv:32
        portarias:33
        proeja:34
        pronatec:35
        publico:36
        rac:37
        registro:38
        sebib:39
        secretaria:40
        sistemas:41
        software:42
        suporteed:43
        tele:44
      dest: /etc/projid
      mode: 0600

  - name: setup project quota
    shell: /usr/sbin/xfs_quota -x -c 'project -s {{ item }}' /arquivos/grupos
    loop:
      - almoxtele
      - cgeral
      - cgp
      - coger
      - comaf
      - compras
      - comunicacao
      - contratos
      - corac
      - cotel
      - ctic
      - cursoad
      - dam
      - depe
      - depx
      - direcao
      - drivers
      - edfisica
      - escultura
      - estagios
      - eventos
      - extensao
      - financeiro
      - gabinete
      - geden
      - gtcarreira
      - gtmemoria
      - licenciatura
      - matematica
      - orcamento
      - pesquisa
      - pocv
      - portarias
      - proeja
      - pronatec
      - publico
      - rac
      - registro
      - sebib
      - secretaria
      - sistemas
      - software
      - suporteed
      - tele

  - name: Set group limits on /arquivos/grupos
    xfs_quota:
      type: project
      mountpoint: /arquivos/grupos
      name: "{{ item.folder }}"
      bhard: "{{ item.quota }}"
    loop: 
      - {folder: 'almoxtele', quota: '1g' }
      - {folder: 'cgeral', quota: '1g' }
      - {folder: 'cgp', quota: '20g' }
      - {folder: 'coger', quota: '2g' }
      - {folder: 'comaf', quota: '10g' }
      - {folder: 'compras', quota: '10g' }
      - {folder: 'comunicacao', quota: '1g' }
      - {folder: 'contratos', quota: '7g' }
      - {folder: 'corac', quota: '4g' }
      - {folder: 'cotel', quota: '10g' }
      - {folder: 'ctic', quota: '4g' }
      - {folder: 'cursoad', quota: '6g' }
      - {folder: 'dam', quota: '8g' }
      - {folder: 'depe', quota: '3g' }
      - {folder: 'depx', quota: '6g' }
      - {folder: 'direcao', quota: '6g' }
      - {folder: 'drivers', quota: '10g' }
      - {folder: 'edfisica', quota: '3g' }
      - {folder: 'escultura', quota: '4g' }
      - {folder: 'estagios', quota: '1g' }
      - {folder: 'extensao', quota: '6g' }
      - {folder: 'financeiro', quota: '4g' }
      - {folder: 'gabinete', quota: '15g' }
      - {folder: 'geden', quota: '2g' }
      - {folder: 'gtcarreira', quota: '1g' }
      - {folder: 'gtmemoria', quota: '16g' }
      - {folder: 'licenciatura', quota: '15g' }
      - {folder: 'matematica', quota: '1g' }
      - {folder: 'orcamento', quota: '3g' }
      - {folder: 'pesquisa', quota: '4g' }
      - {folder: 'portarias', quota: '2g' }
      - {folder: 'proeja', quota: '1g' }
      - {folder: 'pronatec', quota: '2g' }
      - {folder: 'publico', quota: '10g' }
      - {folder: 'rac', quota: '7g' }
      - {folder: 'registro', quota: '4g' }
      - {folder: 'sebib', quota: '2g' }
      - {folder: 'secretaria', quota: '1g' }
      - {folder: 'sistemas', quota: '2g' }
      - {folder: 'software', quota: '18g' }
      - {folder: 'suporteed', quota: '3g' }
      - {folder: 'tele', quota: '26g' }
 
  - name: Arquivo smb.conf
    copy:
      src: arquivos/smb.conf
      dest: /etc/samba/smb.conf
      owner: root
      group: root
      mode: 0644
    when: ansible_os_family == 'Debian'
    notify:
    - reload samba

# ### Início Pasta Home
#   - name: create home directory
#     file:
#         path: /arquivos/home
#         state: directory
#         owner: root
#         group: 'domain admins'
#         mode: 0770
#     notify:
#     - reload samba

#   - name: Sets default ACL user
#     acl:
#       path: /arquivos/home
#       etype: user
#       permissions: rwx      
#       state: present

#   - name: Sets default ACL user
#     acl:
#       path: /arquivos/home
#       etype: user
#       permissions: rwx
#       default: yes
#       state: present

#   - name: Sets ACL for administrator
#     acl:
#       path: /arquivos/home
#       entity: administrator
#       etype: user
#       permissions: rwx      
#       state: present

#   - name: Sets default ACL for administrator
#     acl:
#       path: /arquivos/home
#       entity: administrator
#       etype: user
#       permissions: rwx
#       default: yes
#       state: present

#   - name: Sets ACL for Usuarios conectados
#     acl:
#       path: /arquivos/home
#       entity: '3004'
#       etype: group
#       permissions: r-x      
#       state: present

#   - name: Sets ACL for Domain Admins
#     acl:
#       path: /arquivos/home
#       entity: 'domain admins'
#       etype: group
#       permissions: rwx
#       state: present

#   - name: Sets default ACL for Domain Admins
#     acl:
#       path: /arquivos/home
#       entity: 'domain admins'
#       etype: group
#       permissions: rwx
#       default: yes
#       state: present

#   - name: Sets default ACL for group
#     acl:
#       path: /arquivos/home
#       etype: group
#       permissions: ---
#       default: yes
#       state: present

#   - name: Sets default ACL for mask
#     acl:
#       path: /arquivos/home
#       etype: mask
#       permissions: ---
#       default: yes
#       state: present
  
#   - name: Sets default ACL for other
#     acl:
#       path: /arquivos/home
#       etype: other
#       permissions: ---
#       default: yes
#       state: present
  
# ### Fim Pasta Home

# ### Publico Inicio
#   - name: cria diretório publico
#     file:
#         path: /arquivos/grupos/publico
#         state: directory
#         owner: root
#         group: 'domain users'
#         mode: 0770
#         recurse: yes

#   - name: domain users on public
#     acl:
#       path: /arquivos/grupos/publico
#       entity: '513'
#       etype: group
#       permissions: rwx  
#       state: present
  
#   - name: domain users on public
#     acl:
#       path: /arquivos/grupos/publico
#       entity: '513'
#       etype: group
#       permissions: rwx
#       default: yes
#       state: present
# ### Publico Fim

# ### Drivers Inicio
#   - name: cria diretório drivers
#     file:
#         path: /arquivos/grupos/drivers
#         state: directory
#         owner: root
#         group: "domain admins"
#         mode: 0775
#         recurse: yes
        
#   - name: Disable auto-granting permissions for the primary group of user accounts
#     acl:
#       path: /arquivos/grupos/drivers
#       etype: group
#       permissions: ---
#       default: yes
#       state: present
  
#   - name: Disable auto-granting permissions for the primary group of user accounts
#     acl:
#       path: /arquivos/grupos/drivers      
#       etype: group
#       permissions: ---      
#       state: present

#   - name: domain users on drivers
#     acl:
#       path: /arquivos/grupos/drivers
#       entity: 'cefetsc\domain users'
#       etype: group
#       permissions: r-x  
#       state: present

#   - name: domain users on drivers
#     acl:
#       path: /arquivos/grupos/drivers
#       entity: 'cefetsc\domain users'
#       etype: group
#       permissions: r-x
#       default: yes
#       state: present
  
#   - name: domain users on drivers
#     acl:
#       path: /arquivos/grupos/drivers
#       entity: 'cefetsc\sj-ctic-manutencao'
#       etype: group
#       permissions: rwx
#       state: present

#   - name: domain users on drivers
#     acl:
#       path: /arquivos/grupos/drivers
#       entity: 'cefetsc\sj-ctic-manutencao'
#       etype: group
#       permissions: rwx
#       default: yes
#       state: present
# ### Drivers Fim

# ### Software Inicio
#   - name: cria diretório software
#     file:
#         path: /arquivos/grupos/software
#         state: directory
#         owner: root
#         group: "domain admins"
#         mode: 0775
#         recurse: yes
        
#   - name: Disable auto-granting permissions for the primary group of user accounts
#     acl:
#       path: /arquivos/grupos/software
#       etype: group
#       permissions: ---
#       default: yes
#       state: present
  
#   - name: Disable auto-granting permissions for the primary group of user accounts
#     acl:
#       path: /arquivos/grupos/software
#       etype: group
#       permissions: ---      
#       state: present

#   - name: domain users on software
#     acl:
#       path: /arquivos/grupos/software
#       entity: 'cefetsc\domain users'
#       etype: group
#       permissions: r-x  
#       state: present

#   - name: domain users on software
#     acl:
#       path: /arquivos/grupos/software
#       entity: 'cefetsc\domain users'
#       etype: group
#       permissions: r-x
#       default: yes
#       state: present
  
#   - name: sj-ctic-manutencao on software
#     acl:
#       path: /arquivos/grupos/software
#       entity: 'cefetsc\sj-ctic-manutencao'
#       etype: group
#       permissions: rwx
#       state: present

#   - name: sj-ctic-manutencao on software
#     acl:
#       path: /arquivos/grupos/software
#       entity: 'cefetsc\sj-ctic-manutencao'
#       etype: group
#       permissions: rwx
#       default: yes
#       state: present
# ### Software Fim

# ### Inicio Compartilhamentos padroes

#   - name: cria diretório 
#     file:
#         path: /arquivos/grupos/{{ item }}
#         state: directory
#         owner: root
#         group: "sj-{{ item }}"
#         mode: 0770
#         recurse: yes
#     loop: "{{ pastas }}"
        
#   - name: Disable auto-granting permissions for the primary group of user accounts
#     acl:
#       path: /arquivos/grupos/{{ item }}
#       etype: group
#       permissions: ---
#       default: yes
#       state: present
#     loop: "{{ pastas }}"

#   - name: Disable auto-granting permissions for the primary group of user accounts
#     acl:
#       path: /arquivos/grupos/{{ item }}
#       etype: group
#       permissions: ---      
#       state: present
#     loop: "{{ pastas }}"

#   - name: Disable auto-granting permissions for the primary others of user accounts
#     acl:
#       path: /arquivos/grupos/{{ item }}
#       etype: other
#       permissions: ---
#       default: yes
#       state: present
#     loop: "{{ pastas }}"

#   - name: permissoes de grupo
#     acl:
#       path: /arquivos/grupos/{{ item }}
#       entity: 'cefetsc\sj-{{ item }}'
#       etype: group
#       permissions: rwx  
#       state: present      
#     loop: "{{ pastas }}"

#   - name: permissoes padroes de grupo
#     acl:
#       path: /arquivos/grupos/{{ item }}
#       entity: 'cefetsc\sj-{{ item }}'
#       etype: group
#       permissions: rwx
#       default: yes
#       state: present
#     loop: "{{ pastas }}"

# ### FIM Compartilhamentos padroes

  handlers:
    - name: reload samba
      shell: smbcontrol all reload-config
