- hosts: proxmox_nuvem
  roles:
    - ../roles/docker
  
  tasks:
  
  - name: Cria usuário ctic
    user:
      name: ctic
      shell: /bin/bash

  - name: Adicionar entrada da chave pública no /home/ctic/.ssh/authorized_keys (Monitoramento)
    authorized_key:
      user: ctic
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEArgRS9p4JBq6CGuugYkf8PW7lejJpcJzDdjntND8wKhGUibkZRXcrxI40ClDEp7xLPzIzx6YSyV77AA16ers6AZs83FVSQY/sVO/qTXReyjHKJ1UhB3NQWsMI6XO+mcHFef50WLJ4rHd6b3A8swwF4XK4UtF8K6cDtJnJ1w4DmGwf3uAec0dUWF7UF4nP9VkTbH4bWETHPO7VXy5AcXx3rkzFF6+krtvrUHvC6QlzcUT0ofqb3mLBbWstaznE/lqXRFqHVwkkSLTy476qYM5286+UOTfTcwjsVCiohpoihPGWp4UE8ROKSmP8wLdYGHEJrB9k5FJGkZ5RjLhQ9ZIW9Dn/cgqFjOpvICe+26Zc7qaKTDp9vTCVkrZ94RV1e8gWlwbWcdNavuvpKcIxaNVmsxZ3RUiI5yewdGR3PCEbRkBiKq49E9cmitgbYWnn1jTQz9XXFSXL2MxRA4df6khmPZtKukvdjljt4jfbR40CZ5Q6VtJLO4yN7oYUWE+z3+YJtalT2VYO+L12phVAwjLlwn7JXijzXckBt6mCtTmQFCLBek/Y3EGdYpKnGLCfwvenpebxUOrhZFX8RJiHH8RQqUVv9LYtCdt88RdzAG15FlHufYQQHC+t2nZDrtW+XHpLBPgLFmbfDf03OIfIg/hxPwCDSPKqWgnpWJukdmuVze8= root@monitoramento"

  - name: Adicionar entrada da chave pública no /home/ctic/.ssh/authorized_keys (Humberto)
    authorized_key:
      user: ctic
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYymPFCq/EpbDr9Y5az6z6s3EO1WiiHboeyB94dKSplOG6GSddtwSu4WTr+QSPNks7farRQtAsQUi4j93fVD+T6Nt8k6nWLpbtUx2DLp17rsqi67RO1QixdywwcZwdYCaBztmaZlfPHVVC/rBXeonj8uz51AgpYrQCvnOXrCNWt6m7OpYn3b+AdUC3A3gu8b2KW7cmS1pLZMctfvAbMcFd93a4qO6J8J5dX/ZGG2o/l8Tt82GLGam+3x5Jyi6qa61RxHAbjibdo0WoSrQdGh0bU8twvaTi9bbdeOqa0UVdxDWfpAZY/HBxfRnb9FSVCb+BB9sDB3eyS0CC7KajFqe5 humbertos@sj-ctic-37246"

  - name: Adicionar entrada da chave pública no /home/ctic/.ssh/authorized_keys (Gabriel)
    authorized_key:
      user: ctic
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxZ6W+iZn1dlWBBxLI3ZHup8LRGk4YpnynlG8Fm4oLdM/2fWKupyl8SJDity0m13AVQBMgpR2k/BA1HLFnWjPpxsjsA03ORTVFG3zGN8Yqb0LRuPfpXmQTQtVtGkN7FD4JKyzFeY+G4J0K3mVjOO2F8pGLvrota6q0/8fNfMsHt0uDZpC9c34qM6Xq72ZChJhnq4JY0QT6fzu2BmVnjDz4eBDlrsbtzdgkNF+z1jLdd4xSYgqFhUIrhU8Bsf6vGQMR0CRFh8huKaDCb4/y2F0NmIX0Y5ycwNfOHwvUoIYJMgv0bWv8Ewfg1MsEQ2MxN67H/4/zmMjo9jM7c40R7nmFwhm4pMMCpH8R7DoLAm4g1cKt80GXaef+7OBuluVcV6qOzaIMhBhOxjZomBgw/fjnUSjWrwJEHXNsAE8/gQLaM6OyMVl0L53FL1f8CuhQC618yge9DhM2yDw7IBxxteyA6Mp1GNPSx0HFFqisEZD0q7ZxW3PQMaTqM3Gdf+ONTP1tGbEirPn3YB3erqaYwirRNERcOpJqh/h9ahi8A9HLmSgOB0JGwKPS39ZBDU4OplIWhHY4QT6orzbrO/IkNXv7DxKQjt9N/kytVpP7MNgB6Mrepi4FDA2OUNKYCZ31c29SFOAUWjjd6K5r4W3JTbJtxVjME4/ifd6oQQHFdNIl2w== gabriel.souza@sj-ctic-29736"

  - name: Adiciona no grupo docker
    user:
      name: "{{item}}"
      groups: docker
      append: yes
    with_items:
      - ctic

  - name: Regra que libera a comunicação entre VMs de mesma VLAN
    iptables:
      table: filter
      chain: FORWARD
      in_interface: vmbr0
      out_interface: vmbr0
      jump: ACCEPT

  - name: Valor 1 para net.bridge.bridge-nf-call-iptables (require rke)
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: "1"
      sysctl_set: yes

  - name: Copiando arquivo /etc/iptables.rules
    copy:
      src: proxmox/iptables.rules
      dest: /etc/iptables.rules
      owner: root
      group: root
      mode: 0644

- hosts: proxmox
  tasks:
  
  - name: Adicionar entrada da chave pública no /root/.ssh/authorized_keys (Monitoramento)
    authorized_key:
      user: root
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEArgRS9p4JBq6CGuugYkf8PW7lejJpcJzDdjntND8wKhGUibkZRXcrxI40ClDEp7xLPzIzx6YSyV77AA16ers6AZs83FVSQY/sVO/qTXReyjHKJ1UhB3NQWsMI6XO+mcHFef50WLJ4rHd6b3A8swwF4XK4UtF8K6cDtJnJ1w4DmGwf3uAec0dUWF7UF4nP9VkTbH4bWETHPO7VXy5AcXx3rkzFF6+krtvrUHvC6QlzcUT0ofqb3mLBbWstaznE/lqXRFqHVwkkSLTy476qYM5286+UOTfTcwjsVCiohpoihPGWp4UE8ROKSmP8wLdYGHEJrB9k5FJGkZ5RjLhQ9ZIW9Dn/cgqFjOpvICe+26Zc7qaKTDp9vTCVkrZ94RV1e8gWlwbWcdNavuvpKcIxaNVmsxZ3RUiI5yewdGR3PCEbRkBiKq49E9cmitgbYWnn1jTQz9XXFSXL2MxRA4df6khmPZtKukvdjljt4jfbR40CZ5Q6VtJLO4yN7oYUWE+z3+YJtalT2VYO+L12phVAwjLlwn7JXijzXckBt6mCtTmQFCLBek/Y3EGdYpKnGLCfwvenpebxUOrhZFX8RJiHH8RQqUVv9LYtCdt88RdzAG15FlHufYQQHC+t2nZDrtW+XHpLBPgLFmbfDf03OIfIg/hxPwCDSPKqWgnpWJukdmuVze8= root@monitoramento"

  - name: Adicionar entrada da chave pública no /root/.ssh/authorized_keys (Humberto)
    authorized_key:
      user: root
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYymPFCq/EpbDr9Y5az6z6s3EO1WiiHboeyB94dKSplOG6GSddtwSu4WTr+QSPNks7farRQtAsQUi4j93fVD+T6Nt8k6nWLpbtUx2DLp17rsqi67RO1QixdywwcZwdYCaBztmaZlfPHVVC/rBXeonj8uz51AgpYrQCvnOXrCNWt6m7OpYn3b+AdUC3A3gu8b2KW7cmS1pLZMctfvAbMcFd93a4qO6J8J5dX/ZGG2o/l8Tt82GLGam+3x5Jyi6qa61RxHAbjibdo0WoSrQdGh0bU8twvaTi9bbdeOqa0UVdxDWfpAZY/HBxfRnb9FSVCb+BB9sDB3eyS0CC7KajFqe5 humbertos@sj-ctic-37246"

  - name: Adicionar entrada da chave pública no /root/.ssh/authorized_keys (Gabriel)
    authorized_key:
      user: root
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxZ6W+iZn1dlWBBxLI3ZHup8LRGk4YpnynlG8Fm4oLdM/2fWKupyl8SJDity0m13AVQBMgpR2k/BA1HLFnWjPpxsjsA03ORTVFG3zGN8Yqb0LRuPfpXmQTQtVtGkN7FD4JKyzFeY+G4J0K3mVjOO2F8pGLvrota6q0/8fNfMsHt0uDZpC9c34qM6Xq72ZChJhnq4JY0QT6fzu2BmVnjDz4eBDlrsbtzdgkNF+z1jLdd4xSYgqFhUIrhU8Bsf6vGQMR0CRFh8huKaDCb4/y2F0NmIX0Y5ycwNfOHwvUoIYJMgv0bWv8Ewfg1MsEQ2MxN67H/4/zmMjo9jM7c40R7nmFwhm4pMMCpH8R7DoLAm4g1cKt80GXaef+7OBuluVcV6qOzaIMhBhOxjZomBgw/fjnUSjWrwJEHXNsAE8/gQLaM6OyMVl0L53FL1f8CuhQC618yge9DhM2yDw7IBxxteyA6Mp1GNPSx0HFFqisEZD0q7ZxW3PQMaTqM3Gdf+ONTP1tGbEirPn3YB3erqaYwirRNERcOpJqh/h9ahi8A9HLmSgOB0JGwKPS39ZBDU4OplIWhHY4QT6orzbrO/IkNXv7DxKQjt9N/kytVpP7MNgB6Mrepi4FDA2OUNKYCZ31c29SFOAUWjjd6K5r4W3JTbJtxVjME4/ifd6oQQHFdNIl2w== gabriel.souza@sj-ctic-29736"

  - name: Desabilita acesso ssh com senha
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      insertafter: '^#PasswordAuthentication'
      line: 'PasswordAuthentication no'
    notify: restart_sshd

#NAO ESQUECER DE COLOCAR NO pre-up no network interfaces DE CADA MAQUINA
#
# EXEMPLO:
# 
# auto vmbr0.900
# iface vmbr0.900 inet static
# 	address  172.18.119.X
# 	netmask  255.255.255.0
# 	gateway  172.18.119.254
# 	pre-up iptables-restore < /etc/iptables.rules

  - name: Configura repositório pve-no-subscription
    apt_repository:
      repo: deb http://download.proxmox.com/debian/pve stretch pve-no-subscription
      state: present

  - name: Remove repositório pve-enterprise
    apt_repository:
      repo: deb https://enterprise.proxmox.com/debian/pve stretch pve-enterprise
      filename: pve-enterprise
      state: absent

  - name: Upgrade all packages to the latest version
    apt: name="*" state=latest
    when: ansible_os_family == 'Debian'

  - name: Update dist to the latest version
    apt:
      upgrade: dist

  - name: Instala alguns pacotes 
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - vim
      - aptitude
    when: ansible_os_family == 'Debian'

  handlers:
    - name: restart_sshd
      service:
        name: ssh
        state: restarted 

- hosts: proxmoxblade2.sj.ifsc.edu.br
  tasks:
  
  - name: Instala pacotes nfs-kernel-server pro proxmox2
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - nfs-kernel-server

  - name: Adicionar entrada /var/nfs-export no /etc/exports no proxmox2
    lineinfile:
      regexp: '^/var/nfs-export'
      path: /etc/exports
      line: '/var/nfs-export       191.36.8.1(rw,sync,no_subtree_check) 191.36.8.5(rw,sync,no_subtree_check) 191.36.8.9(rw,sync,no_subtree_check) 191.36.8.11(rw,sync,no_subtree_check) 191.36.8.21(rw,sync,no_subtree_check) 191.36.8.22(rw,sync,no_subtree_check) 191.36.8.23(rw,sync,no_subtree_check) 191.36.8.25(rw,sync,no_subtree_check) 191.36.8.26(rw,sync,no_subtree_check) 191.36.8.27(rw,sync,no_subtree_check)'
    notify: restart_nfs-server

  handlers:
    - name: restart_nfs-server
      service:
        name: nfs-server
        state: restarted 