- hosts: vms_nuvem
  roles:
    - ../roles/docker
  
  tasks:

  - name: update apt cache
    apt: update_cache=yes

  - name: Instala alguns pacotes 
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - aptitude
      - vim      
      - python-apt
      - bash-completion
      - open-iscsi
    when: ansible_os_family == 'Debian'

  - name: Upgrade all packages to the latest version
    apt: name="*" state=latest
    when: ansible_os_family == 'Debian'

  - name: Update dist to the latest version
    apt:
      upgrade: dist

  - name: Valor 1 para net.bridge.bridge-nf-call-iptables (require rke)
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: "1"
      sysctl_set: yes

  - name: Carrega os modulos para o rke automaticamente no boot
    copy:
      content: |
        br_netfilter
        ip6_udp_tunnel
        ip_set
        ip_set_hash_ip
        ip_set_hash_net
        iptable_filter
        iptable_nat
        iptable_mangle
        iptable_raw
        nf_conntrack_netlink
        nf_conntrack
        nf_conntrack_ipv4
        nf_defrag_ipv4
        nf_nat
        nf_nat_ipv4
        nf_nat_masquerade_ipv4
        nfnetlink
        udp_tunnel
        veth
        vxlan
        x_tables
        xt_addrtype
        xt_conntrack
        xt_comment
        xt_mark
        xt_multiport
        xt_nat
        xt_recent
        xt_set
        xt_statistic
        xt_tcpudp
      dest: /etc/modules-load.d/rke.conf
      owner: root
      group: root
      mode: 0644

  - name: update-alternatives iptables
    alternatives:
      name: iptables
      path: /usr/sbin/iptables-legacy

  - name: update-alternatives ip6tables
    alternatives:
      name: ip6tables
      path: /usr/sbin/ip6tables-legacy

  - name: Carrega o modulo rbd
    modprobe:
      name: rbd
      state: present

  - name: Carrega o modulo rbd automaticamente no boot
    copy:
      content: |
        rbd
      dest: /etc/modules-load.d/rbd.conf
      owner: root
      group: root
      mode: 0644