### É necessário que a chave rsa pública e privada do monitoramento esteja em /root/.ssh
### Necessário executar esse comando na mão: git clone git@gitlab.com:ctic-sje-ifsc/inventory_ansible.git
- hosts: wol.sj.ifsc.edu.br
  tasks:
  - name: Instalar os pacotes para o Ansible - Linux Debian
    apt: name=ansible state=latest
  - name: Pacotes padrao
    apt: name={{ packages }} state=latest
    vars:
      packages:
      - ansible
      - nfs-common
      - vim
      - curl
      - ethtool
      - git
      - tcpdump
      - usbutils
      - net-tools
      - dnsutils
      - ipcalc
      - etherwake
      - python-apt

- hosts: wol.sj.ifsc.edu.br
  roles:
  - role: ../roles/grub
    tipo: grub_soh_lin
  tasks:
  - name: Cria diretorio para o Ansible
    file:
      path: /root/ansible
      state: directory
      owner: root
      group: root
      mode: 0644
    when: ansible_os_family == 'Debian'

  - name: Copiando arquivo de configuração do Ansible
    copy:
      src: wol/ansible.cfg
      dest: /etc/ansible/ansible.cfg
      owner: root
      group: root
      mode: 0644

  - name: Copiando playbook do Wake On Lan
    copy:
      src: wol/wol.yml
      dest: /root/ansible/wol.yml
      owner: root
      group: root
      mode: 0644

  - name: Copiando playbook para pegar os facts
    copy:
      src: wol/get_facts.yml
      dest: /root/ansible/get_facts.yml
      owner: root
      group: root
      mode: 0644

  - name: Copiando arquivo de configuracao do ssh
    copy:
      src: wol/ssh_config
      dest: /etc/ssh/ssh_config
      owner: root
      group: root
      mode: 0644

  - name: Cron rodar playbook get_facts - laboratorios
    cron:
      name: "Pegar facts das maquinas de laboratorio"
      minute: "10"
      job: "/usr/bin/ansible-playbook -i /root/inventory_ansible/laboratorios/host /root/ansible/get_facts.yml > /tmp/facts_lab.log"

  - name: Cron rodar playbook get_facts - administrativos
    cron:
      name: "Pegar facts das maquinas administrativas"
      minute: "10"
      job: "/usr/bin/ansible-playbook -i /root/inventory_ansible/administrativo/host /root/ansible/get_facts.yml > /tmp/facts_adm.log"

  - name: Cron rodar git pull
    cron:
      name: "Atualizar inventory_ansible"
      minute: "10"
      job: "/usr/bin/git -C /root/inventory_ansible/ pull git@gitlab.com:ctic-sje-ifsc/inventory_ansible.git > /tmp/git_pull.log"

  - name: Cron ligar maquina ricardo1
    cron:
      name: "Maquina Ricardo"
      weekday: 1,3,4,5
      minute: "15"
      hour: "8"
      job: "/usr/sbin/etherwake -i eth0 78:24:af:9a:89:b8 -b"

  - name: Cron ligar maquina ricardo2
    cron:
      name: "Maquina Ricardo2"
      weekday: 2
      minute: "30"
      hour: "12"
      job: "/usr/sbin/etherwake -i eth0 78:24:af:9a:89:b8 -b"

  - name: Cron ligar maquina Gabriel
    cron:
      name: "Maquina Gabriel"
      weekday: 1-5
      minute: "50"
      hour: "6"
      job: "/usr/sbin/etherwake -i eth0 fc:aa:14:fc:66:09 -b"

  - name: Cron ligar maquina Humberto
    cron:
      name: "Maquina Humberto"
      weekday: 1-5
      minute: "50"
      hour: "6"
      job: "/usr/sbin/etherwake -i eth0 f0:4d:a2:e6:c5:39 -b"

  - name: Cron ligar maquina Odilson
    cron:
      name: "Maquina Odilson"
      weekday: 1-5
      minute: "20"
      hour: "7"
      job: "/usr/sbin/etherwake -i eth10 f0:4d:a2:e4:1b:05 -b"

  - name: Adicionar entrada da chave pública no /root/.ssh/authorized_keys (Monitoramento)
    authorized_key:
      user: root
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEArgRS9p4JBq6CGuugYkf8PW7lejJpcJzDdjntND8wKhGUibkZRXcrxI40ClDEp7xLPzIzx6YSyV77AA16ers6AZs83FVSQY/sVO/qTXReyjHKJ1UhB3NQWsMI6XO+mcHFef50WLJ4rHd6b3A8swwF4XK4UtF8K6cDtJnJ1w4DmGwf3uAec0dUWF7UF4nP9VkTbH4bWETHPO7VXy5AcXx3rkzFF6+krtvrUHvC6QlzcUT0ofqb3mLBbWstaznE/lqXRFqHVwkkSLTy476qYM5286+UOTfTcwjsVCiohpoihPGWp4UE8ROKSmP8wLdYGHEJrB9k5FJGkZ5RjLhQ9ZIW9Dn/cgqFjOpvICe+26Zc7qaKTDp9vTCVkrZ94RV1e8gWlwbWcdNavuvpKcIxaNVmsxZ3RUiI5yewdGR3PCEbRkBiKq49E9cmitgbYWnn1jTQz9XXFSXL2MxRA4df6khmPZtKukvdjljt4jfbR40CZ5Q6VtJLO4yN7oYUWE+z3+YJtalT2VYO+L12phVAwjLlwn7JXijzXckBt6mCtTmQFCLBek/Y3EGdYpKnGLCfwvenpebxUOrhZFX8RJiHH8RQqUVv9LYtCdt88RdzAG15FlHufYQQHC+t2nZDrtW+XHpLBPgLFmbfDf03OIfIg/hxPwCDSPKqWgnpWJukdmuVze8= root@monitoramento"

  - name: Adicionar entrada da chave pública no /root/.ssh/authorized_keys (Humberto)
    authorized_key:
      user: root
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYymPFCq/EpbDr9Y5az6z6s3EO1WiiHboeyB94dKSplOG6GSddtwSu4WTr+QSPNks7farRQtAsQUi4j93fVD+T6Nt8k6nWLpbtUx2DLp17rsqi67RO1QixdywwcZwdYCaBztmaZlfPHVVC/rBXeonj8uz51AgpYrQCvnOXrCNWt6m7OpYn3b+AdUC3A3gu8b2KW7cmS1pLZMctfvAbMcFd93a4qO6J8J5dX/ZGG2o/l8Tt82GLGam+3x5Jyi6qa61RxHAbjibdo0WoSrQdGh0bU8twvaTi9bbdeOqa0UVdxDWfpAZY/HBxfRnb9FSVCb+BB9sDB3eyS0CC7KajFqe5 humbertos@sj-ctic-37246"

  - name: Adicionar entrada da chave pública no /root/.ssh/authorized_keys (Gabriel)
    authorized_key:
      user: root
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxZ6W+iZn1dlWBBxLI3ZHup8LRGk4YpnynlG8Fm4oLdM/2fWKupyl8SJDity0m13AVQBMgpR2k/BA1HLFnWjPpxsjsA03ORTVFG3zGN8Yqb0LRuPfpXmQTQtVtGkN7FD4JKyzFeY+G4J0K3mVjOO2F8pGLvrota6q0/8fNfMsHt0uDZpC9c34qM6Xq72ZChJhnq4JY0QT6fzu2BmVnjDz4eBDlrsbtzdgkNF+z1jLdd4xSYgqFhUIrhU8Bsf6vGQMR0CRFh8huKaDCb4/y2F0NmIX0Y5ycwNfOHwvUoIYJMgv0bWv8Ewfg1MsEQ2MxN67H/4/zmMjo9jM7c40R7nmFwhm4pMMCpH8R7DoLAm4g1cKt80GXaef+7OBuluVcV6qOzaIMhBhOxjZomBgw/fjnUSjWrwJEHXNsAE8/gQLaM6OyMVl0L53FL1f8CuhQC618yge9DhM2yDw7IBxxteyA6Mp1GNPSx0HFFqisEZD0q7ZxW3PQMaTqM3Gdf+ONTP1tGbEirPn3YB3erqaYwirRNERcOpJqh/h9ahi8A9HLmSgOB0JGwKPS39ZBDU4OplIWhHY4QT6orzbrO/IkNXv7DxKQjt9N/kytVpP7MNgB6Mrepi4FDA2OUNKYCZ31c29SFOAUWjjd6K5r4W3JTbJtxVjME4/ifd6oQQHFdNIl2w== gabriel.souza@sj-ctic-29736"

  - name: Adicionar entrada da chave pública no /root/.ssh/authorized_keys (Ricardo)
    authorized_key:
      user: root
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHGABNL4VckVVEjgNJWrfFg6LqsypziY18hzVx12F/MA/q6RSJY7Wg/X5HRG7MKEdUezKCz7b6eSaTDP982Di1KD3YFLOnl8IJOf4fwxkwX7y7MX0xozDuJlhtMlJD8/g/n+hfybzsbQQkT0FC3onfOni7V8UfiNYq4wYNj6Vp0uj5eKNXUYeMe5yKLkCQa5r3pIH/4mTj/TF0pWMBjntTjxlstG7Z0a0r77UzMjFZAdGjfNfW3uSm3icyo1StIJ88I7WatJnhPDK3K7S/l8Ls+HU5tFh7AuPTVqPuiLtLEQ11XhcBKdIjewiGD6wfvyFVwCC94mWJnhS7rltIMYIFVZORgB5UuEUvZNevztyWhMb4Ho2Wi4jxSuU2If5huVRSmskeQe750E6FFWl1hB7XRDKGKbWHhG0BOCuB9h8wnpvn9s+7x1vvTdbnEx516JNyRGELtoElG20MYADou1N66yzusN/tdSeBO9BfvD6Sts/5HX8j0NNogF8swJ7DQEj0bbFoqBIeyfnJrQt+YJ85RuN/rexzYPYHEO6K7YR+u2cz4s5AJT9VCSVzVhG6ibj6RcBNCFTdok3qvAnwv5arvIuALeTZLVe+FFu5AKlJ2kQ+dtYqcXyeP5KyoHI2h5WzrxqTl/iOkoSFeTk+jt54DRGwP4kjBgGFdGeeNyzKmQ== rmartins@sj-lin-744396"
