---
#Linux
- name: Adicionar repositório para instalar libssl1.0.0
  apt_repository:
    repo: deb http://ftp.debian.org/debian jessie-backports main
    state: present
    update_cache: yes
  when: ansible_distribution == 'Debian'

- name: Instalar pacotes necessarios para o packettracer
  apt: name=libssl1.0.0 state=latest default_release=jessie-backports
  when: ansible_distribution == 'Debian'

- name: Instalar pacotes necessarios para o packettracer - Linux
  apt: name={{item}} state=latest
  with_items:
    - libqt5webkit5
    - libqt5webkit5-dev
    - libqt5multimedia5
    - libqt5multimedia5-plugins
    - libqt5webkit5-dbg
    - libqt5script5
    - libqt5scripttools5
  when: ansible_distribution == 'Debian'

- name: Baixando e extraindo o packettracer7.tar.gz - Linux Debian
  unarchive:
    src: https://discovirtual.ifsc.edu.br/index.php/s/7LaUM9ofkcWP47c/download
    dest: /opt/
    creates: /opt/pt
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'

- name: Criando o arquivo packettracer7.desktop - Linux Debian
  copy:
    src: packettracer7.desktop
    dest: /usr/share/applications/packettracer7.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

#Unavaliable for Windows
